### ISSUE TITLE
See status of AppRepository syncs (especially failures) in UI

### ISSUE THREAD

**Issue by prydonius** [vmware-tanzu/kubeapps#153]
See also https://github.com/kubeapps/dashboard/issues/7

Since AppRepository syncing is done asynchronously, we can't really report back a status immediately after adding a repo. But the App Repositories configuration page should report the status:

- See when syncs are happening
- See if a sync has failed, check logs of failing sync
- See a healthy status if syncs are succeeding

This will require a read-only list/get/logs for pods in the `kubeapps` namespace.

**Comment by m1small** [comment]
It would be nice to complement this with the number of charts retrieved from that source.

**Comment by absoludity** [comment]
Related, it'd be great to validate the user input when adding a repository (ie. verifying the repo can be contacted with the entered details).

**Comment by dlaloue-vmware** [comment]
+ to improve on repository feedback.
I am facing an issue where all sync jobs are failing, and the only log message available is:

sync
time="2021-09-08T02:00:51Z" level=fatal msg="GET request to [https://releases.rancher.com/server-charts/stable/index.yaml] failed due to status [401]: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>"

when the index.yaml file is actually not requiring any authentication (can get access it from any browser, curl).

**Comment by absoludity** [comment]
The request for the rancher index.yaml does 401 if an authorization header is provided:

```
curl -Is -H "Authorization: foo" https://releases.rancher.com/server-charts/stable/index.yaml | head -n1
HTTP/2 401 
```

Are you certain you didn't define an auth header for the repo? If I do the same request with an empty Authorization header, it's fine:

```
curl -Is -H "Authorization: " https://releases.rancher.com/server-charts/stable/index.yaml | head -n1 
HTTP/2 200 
```

Not sure what more we could log in that specific case, since we can't include the headers. But it would be helpful if the log message indicated whether an authorization header was sent (filled).

**Comment by dlaloue-vmware** [comment]
here is the apprepository CRD generated by the UI (global repository):

apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  creationTimestamp: "2021-09-08T01:48:31Z"
  generation: 2
  name: rancher
  namespace: system-kubeapps
  resourceVersion: "74157222"
  selfLink: /apis/kubeapps.com/v1alpha1/namespaces/system-kubeapps/apprepositories/rancher
  uid: 63c60405-5f45-4348-98ee-f2c7f22fc8b7
spec:
  auth: {}
  filterRule:
    jq: ""
  resyncRequests: 1
  syncJobPodTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
  type: helm
  url: https://releases.rancher.com/server-charts/stable
status:
  status: ""

This is configured via the UI, with no special sync job parameters. So if the job is using Authentication header, i think this would from the code itself, not though user input.

**Comment by antgamdia** [comment]
Closing as the new UI now includes the status plus a tooltip with the error reason:

https://github.com/vmware-tanzu/kubeapps/blob/00346f169e007c2ecde006d38d87f423be068db0/dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx#L131-L142
