### ISSUE TITLE
Basic Forms: K8s resources as drop-down list 

### ISSUE THREAD

**Issue by batiati** [vmware-tanzu/kubeapps#1797]
### Feature

Support to render common k8s resources as drop-down lists, such `secret`, `configmap`, `pvc`, `storageclass`, `crd`, etc.

Similar feature can be found on Rancher's Charts, see the `type` variable on [questions.yaml reference](https://rancher.com/docs/rancher/v2.x/en/catalog/creating-apps/#question-variable-reference) for more details.

### Example

Example of values.schema.json

```
        "storageClass": {
          "type": "string",
          "title": "Storage class",
          "form": true,
          "resource": "storageclass"
        }
```

It shoud render a drop-down list populated with result of `kubectl get storageclass` command.

### Benefits

Allow to deploy charts that rely on the correct selection of external resources, most commonly secrets, config maps and storage classes.

### Drawbacks

Increased time to render the form

**Comment by andresmgot** [comment]
Note that this is quite more complex than other improvements for the form.

 - We would need not only the resource but the API version as well: `storage.k8s.io/v1`. This is because we don't have the logic to auto resolve it (as `kubectl` does) and the API version is required to list elements. We have a [hard-coded list of these versions ](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/ResourceAPIVersion.ts) but it's something we need to substitute at some point.
 - We may need to differ between namespaced or non namespaced elements (secrets vs clusterrole).  This may not be needed since I believe that the Kubernetes API ignores the namespace if requesting a cluster component.
 - Requests of this type are asynchronous, we would need to handle loading components in the form.
 - The form becomes unusable for people without the permissions to list those resources. A user with RBAC permissions to just see components within a namespace won't have permissions to list `storageclasses` which would make the form unusable for them.

IMO it would be a nice addition but it should be treated carefully.

**Comment by batiati** [comment]
We can assume the same behavior of Helm's `lookup` function, where the correct RBAC is required to deploy a chart using that function.

Arguments of `lookup` function from [Helm's reference](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/)
parameter | type
-- | --
apiVersion | string
kind | string
namespace | string
name | string

>Both name and namespace are optional and can be passed as an empty string ("").

So we can use it in the same way on values.schema.json

```
        "storageClass": {
          "type": "string",
          "title": "Storage class",
          "form": true,
          "lookup": {
              "apiVersion": "storage.k8s.io/v1",
              "kind": "storageclass"
           }
        }
```

**Comment by andresmgot** [comment]
yes, with one caveat, if we use `kind` it should be `StorageClass` (I believe that the capital letters are important).

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps. Could be re-opened if more demand on this issue.
