### ISSUE TITLE
Feature Request: Required form values

### ISSUE THREAD

**Issue by rarick** [vmware-tanzu/kubeapps#1924]
It would be great to have a boolean `required` attribute available in `values.schema.json`.

I currently have a form which has some default values in it, while others are required and default to nothing. I find myself frequently skipping these required fields on accident, which causes an error screen to promptly occur. I then have to return and repopulate my fields. This is a problem solved in most web forms by having "required" fields.

This attribute would require the user to enter a value for the field in the form before being able to hit the `submit` button on the deployment form. 

I'm no web developer, so I encourage anyone with more UI/UX experience to weigh in on more typical features found in web form required fields. Below is an initial list of ideas for potential functionality:
- Red asterisk (*) by the field name
- Red border on field if the field is passed without a value (or until a value is entered?)
- Pressing submit before required fields are populated does not deploy the chart
- Could potentially have feedback when pressing submit such as "`ingress.hostname` required"
- Required fields that are hidden become "unrequired"

**Comment by absoludity** [comment]
+1, being able to set `required` or `pattern` or `placeholder` could all be valuable.

**Comment by andresmgot** [comment]
So there are two problems here:
 - When you submit the chart and the installation fails, the values set are cleaned up. This should not happen (and will be fixed separately).
 - It's already possible to set required parameters using JSON schema: https://json-schema.org/understanding-json-schema/reference/object.html#required-properties. You can use that to get an earlier message (even though you'd still need to submit the form to get the error). We would need to translate that "required" property in order to use it in the form to not allow to submit the form is the property is required.
