### ISSUE TITLE
AppRepositories are only availabe on the cluster on which Kubeapps is installed

### ISSUE THREAD

**Issue by zhangchunsheng** [vmware-tanzu/kubeapps#1982]
http://xxx/#/c/default/ns/kube-system/config/repos

I think it should be done on any cluster.

```
AppRepositories can be created on the default cluster only
kubeapps' multi-cluster support currently enables creation of custom app repositories on the cluster on which kubeapps is installed.

You cannot currently create an app repository on an additional cluster.
```

**Comment by absoludity** [comment]
Yes, this isn't a design decision that we don't want to change, it's an implementation detail of the initial multi-cluster support because we need do quite a bit of work to support app repositories in other clusters.

Note that any app repositories that you make available to all namespaces on your kubeapps cluster are available on all namespaces on all clusters, you just can't create per-namespace app repositories on other clusters yet.

**Comment by absoludity** [comment]
Issues which need to be handled before or while designing and implement this:

At the very least, if we blindly push forward with the current AppRepositories but on other clusters, then #1647 Move app repo sync to run in cluster/namespace will need to be designed and implemented first (as currently the sync jbo assumes DB access to the kubeapps backend). That said, it's not yet clear if we want to do this, imo. We need to re-evaluate the concept of app repositories and how we sync and present data from them.

#1358 Import charts from an OCI registry - before pushing for (helm2) AppRepositories on additional clusters, we should, IMO, decide how we're going to present catalogs moving forward... not just for OCI repos, but also for the `hub` style that helm is using, see #2078

**Comment by ppbaena** [comment]
To be closed as we are not considering this feature in our roadmap. We can reconsider to re-open it if there's more demand on this feature.
