### ISSUE TITLE
Unable to add OCI based GCP's Artifact Registry to Kubeapps

### ISSUE THREAD

**Issue by jeunii** [vmware-tanzu/kubeapps#4284]
### Description:

I am trying to add an OCI Registry to the App Repository. The OCI registry is [GCP's Artifact Registry](https://cloud.google.com/artifact-registry/docs/helm/quickstart)

OCI registry type is [supported](https://cloud.google.com/artifact-registry/docs/supported-formats). 

In GCP I have setup a test repo and can successfully deploy a helm release

```
helm install hello-chart oci://europe-west4-docker.pkg.dev/sap-cx-pipeline-prod/quickstart-helm-repo/hello-chart --version 0.1.0

NAME: hello-chart
LAST DEPLOYED: Tue Feb 15 14:31:46 2022
NAMESPACE: default
STATUS: deployed
...
```

I have followed the [guide](https://github.com/kubeapps/kubeapps/blob/main/docs/user/private-app-repository.md#oci-registry) and my config looks like this

![Screen Shot 2022-02-15 at 4 30 31 PM](https://user-images.githubusercontent.com/46089687/154152648-d4c3d18c-efa0-477e-af91-67db8836b952.png)

I can create the repo in kubeapps successfully and its displayed on the UI

![Screen Shot 2022-02-15 at 4 05 06 PM](https://user-images.githubusercontent.com/46089687/154149020-f6076c89-7d95-4047-8a0e-aec5e433b3f4.png)

But when I click on it I get the error

```
Unable to fetch package: Unable to get the available package versions for the package "gcp-artifactory-repo%2Fquickstart-helm-repo%2Fhello-chart" using the plugin "helm.packages": rpc error: code = InvalidArgument desc = Incorrect request.AvailablePackageRef.Identifier, currently just 'foo/bar' patters are supported: gcp-artifactory-repo%2Fquickstart-helm-repo%2Fhello-chart
```

### Steps to reproduce the issue:

1. Create an helm repo of type docker in GCP's artifact registry
2. Create a Service Account in GCP, give it read rights to artifact registry and generate a token
3. Add the repo in App Repository in Kubeapps 

### Describe the results you received:

I cannot view the helm chart in Catalogue section in Kubeapps. Refreshing the repo creates a cronjob which runs succesfully

```
kl apprepo-apps-sync-sap-cx-pipeline-prod-vwrzr-5bdnx -f

I0215 20:45:25.984389       1 sync.go:87] Last checksum: be382368038c7bccbc194240d29e4813bbde973c4db7469a3eee2668fc17b538
time="2022-02-15T20:45:26Z" level=info msg="icon not found" name="quickstart-helm-repo%2Fhello-chart"
I0215 20:45:26.416882       1 sync.go:115] Repository synced, shallow=false
I0215 20:45:26.419472       1 sync.go:124] Stored repository update in cache, repo.URL= https://europe-west4-docker.pkg.dev/sap-cx-pipeline-prod/
I0215 20:45:26.419494       1 sync.go:125] Successfully added the package repository sap-cx-pipeline-prod to database
```

The app repository controller also does not show any error

```
time="2022-02-15T20:45:23Z" level=info msg="Successfully synced 'apps/sap-cx-pipeline-prod'"
time="2022-02-15T20:45:23Z" level=info msg="Event(v1.ObjectReference{Kind:\"AppRepository\", Namespace:\"apps\", Name:\"sap-cx-pipeline-prod\", UID:\"da1febb8-24d2-4d07-8314-ed583d314623\", APIVersion:\"kubeapps.com/v1alpha1\", ResourceVersion:\"142628072\", FieldPath:\"\"}): type: 'Normal' reason: 'Synced' AppRepository synced successfully"
```

### Describe the results you expected:

Expect to see the helm chart and deploy it.

### Additional information you deem important (e.g. issue happens only occasionally):

I also uploaded version 0.2.0 to GCP's artifact repository but it still shows version 0.1.0 in kubeapps UI

In GCP:
![Screen Shot 2022-02-15 at 4 13 43 PM](https://user-images.githubusercontent.com/46089687/154150155-3708b13a-30eb-45d2-9cc2-ea05805dddcb.png)

In Kubeapps after refreshing the repo
![Screen Shot 2022-02-15 at 4 12 57 PM](https://user-images.githubusercontent.com/46089687/154150071-1556f735-c03a-4ace-9c17-aef94bc0f471.png)

I also see such errors

![Screen Shot 2022-02-15 at 4 32 15 PM](https://user-images.githubusercontent.com/46089687/154152860-66936ed7-0e5b-407f-9742-e9fd574cc39f.png)

In GCP

![Screen Shot 2022-02-15 at 4 33 36 PM](https://user-images.githubusercontent.com/46089687/154153026-6f77a5ed-7139-4168-932b-08bd4eef4c54.png)

### Version of Helm, Kubeapps and Kubernetes:

- Kubeapps version

```
v2.4.2
```

**Comment by absoludity** [comment]
Originally [discussed on slack](https://kubernetes.slack.com/archives/C9D3TSUG4/p1644937552021969). I've not bisected to see if it's a recent change since switching to the kubeapps-apis server (assume so) or something we've had in the OCI support from the start (doubt it?), but it seems we've enforced a helm package identifier of `foo/bar` which doesn't work when an OCI repository is itself partitioned with a slash.

**Comment by antgamdia** [comment]
I had a quick look at the issue (I have repro it, but using Harbor) and the problem seems to be twofold:

1. As Michael pointed out at #4716, we are forcing `foo/bar` patterns
2. The `(c *OCIRepoClient) GetChart` in [this file](https://github.com/vmware-tanzu/kubeapps/blob/f41f0dd53ab1b4988342a4036c21659d05375397/pkg/chart/chart.go) below is not prepared to unescape the chart name coming from the database:

````
assets=# SELECT ((info ->> 'ID')) FROM charts WHERE chart_id NOT ILIKE '%bitnami/%';
 oci/kubeapps
 oci/kube%2Fapps
````

but the URL it requests is:

````
I0518 14:26:22.178671       1 chart.go:417] XXX repoURL: https://harbor-repo.vmware.com/agamez
I0518 14:26:22.178732       1 chart.go:422] XXX url: https://harbor-repo.vmware.com/agamez
I0518 14:26:22.178782       1 chart.go:425] XXX ref: harbor-repo.vmware.com/agamez/kube%2Fapps:8.1.2-dev0
````

**Comment by antgamdia** [comment]
As per the comment at  https://github.com/vmware-tanzu/kubeapps/pull/4739#issuecomment-1131825547:

> Hello. Thank you for this. In which release should I be able to test this ?

Hi @jeunii, I'm reopening the issue since I didn't mean to close it before checking it with you first. 

Since the modified component is `kubeapps-apis`, you only have to replace the "official" image with the one we build once a new commit gets merged into the main branch. For instance, you can execute:

````
kubectl scale deploy/kubeapps-internal-kubeappsapis -n kubeapps --replicas=0
kubectl set image deployment/kubeapps-internal-kubeappsapis -n kubeapps kubeappsapis=kubeapps/kubeapps-apis
kubectl scale deploy/kubeapps-internal-kubeappsapis -n kubeapps --replicas=1
````

If it doesn't work, you can always use our local chart; that is, cloning this project and installing the chart defined under `/chart/kubeapps`, which includes the latest build.

Let us know if this PR fixed your issue, otherwise, we will still continue to investigate it!

**Comment by ppbaena** [comment]
Hi @jeunii 👋 , could you take a look on this? Do you have any update related to this issue?
