### ISSUE TITLE
helm repositories being reported even if helm plugin is not enabled

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4340]
### Description:

by default, a bitnami app repository is automatically created by the chart.
even when the helm plugin is not enabled, the "repository" page lists those app repositories.

### Steps to reproduce the issue:

create a default install with helm plugin disabled and flux enabled.

### Describe the results you received:

the app repository page displays the app repositories available in the cluster.

### Describe the results you expected:

as the helm plugin is disabled, those app repositories should not be available, and it is confusing to the user.

The new repository api is not yet available, and is likely the source of the issue. But in order to avoid the confusion, the old helm repository api should be updated to check whether the helm plugin is enabled/disabled react accordingly.

### Version of Helm, Kubeapps and Kubernetes:

kubeapps v2.4.3

**Comment by absoludity** [comment]
Thanks @dlaloue-vmware . Yes, related to this, I'm playing with a chart change that doesn't even install the `AppRepository` CRD nor postgres nor assetsvc etc., if the helm plugin isn't enabled. #3496 is the long-term plan for handling package repositories generically, but that's a large task, so in the mean-time perhaps we can update the UI to instead display the link to the docs (I recently updated so that the empty repo page displays links to the docs for carvel and flux with #4331, but we could also display this temporarily instead of helm repos when helm is not enabled).

**Comment by dlaloue-vmware** [comment]
yes, displaying the link to the docs would work as well.

**Comment by absoludity** [comment]
https://github.com/bitnami/charts/pull/9204 is the chart PR to remove the dependencies when not being used (postgres, app-repository controller etc.), and with that, the actual app repositories are no longer displayed, but still need to update the actual dashboard so it provides the links to the docs rather than empty (and irrelevant) tables for app repositories (for now).

**Comment by absoludity** [comment]
The main issue here has been fixed as per the linked chart change above, but we'd still want to include a link to the docs and disable the AddRepo buttons etc. when Helm is not enabled.

**Comment by absoludity** [comment]
I'm closing this since the main issue is fixed and the remaining small UI improvements will be done as part of the integration of the new pkg repositories API.
