### ISSUE TITLE
Component for editing package installation values in table mode

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4396]
### Description:

Currently Kubeapps is capable of dynamically generating a form with chart values metadata so that users can use it to adjust installation values.
Sometimes this kind of dynamic forms are a bit sluggish, specially when the form is very large. Also, finding the right control that corresponds to the right installation value is sometimes complicated.

It could be nice being able to edit installation values in table mode. One row -> one installation value.
Something like TMC colleagues have done:

| Key                | Type    | Description                         | Value |
|--------------------|---------|-------------------------------------|-------|
| global             |         | Global configuration                |       |
| ![image](https://user-images.githubusercontent.com/67455978/157249735-a4c107e0-9218-4173-86bc-2780f28af014.png)imageRegistry | string  | Global image registry               |  docker.io/...     |
| ![image](https://user-images.githubusercontent.com/67455978/157249735-a4c107e0-9218-4173-86bc-2780f28af014.png)imagePullSecrets | array   |  Secrets....                                   |   ["secret1"] *    |
| commonAnnotations  | object   | Annotations common to all resources |  {}     |
| startupProbe       |         |                                     |       |
| ![image](https://user-images.githubusercontent.com/67455978/157249735-a4c107e0-9218-4173-86bc-2780f28af014.png)timeoutSeconds   | integer | Timeout seconds for startup probe   |  20 *     |

Information presented on screen would be the same, but smaller in size and quicker to edit than the form edition. It would be straight forward to know the corresponding package value key.
The only editable part would be the `Value` column. Edited values would have some kind of visual sign (e.g. asterisk, different color, etc.)

**Comment by absoludity** [comment]
This might also make it simpler for us to have a standard way to render forms both for simple form components as well as schema items for extra fields required by packaging plugins.

**Comment by antgamdia** [comment]
More updates here:

- As the schema increases, dealing with a real-time-in-yaml-param-setting process is unbearable. I have switched to a new model where we store the modifications and then apply them altogether as user's request.
- Unfortunately, this is still not solving the rendering time when the schema is long. I think I'll go with an external Table solution like https://tanstack.com/table. However, I wanted to have something working before going deeper into the table think.
- Some good news: even being in the table, I think we can reuse some logic for setting the <input>, <toggle> and other components to ease the UX when entering data.
- I haven't thought yet of the "custom forms" feature. I think we have to preserve this functionality as it is being used by our community. However, this is for a 2nd stage.

![newParams](https://user-images.githubusercontent.com/11535726/186962574-80c709fc-82d4-4d72-af48-6d725e220d97.gif)

**Comment by castelblanque** [comment]
> dealing with a real-time-in-yaml-param-setting process is unbearable. I have switched to a new model where we store the modifications and then apply them altogether as user's request.

Yep, too much stuff for browser's JS. Probably the best way to go is to stack the changes and apply them as you did.

>apply them altogether as user's request.

I don't think we should put on the user's decision the result of a technical limitation (i.e. remembering to click "sync").
Is it sluggish always for all Yaml sizes? Could we behave differently in two scenarios (big and small yaml files?).
I'm a bit reluctant about having that "Sync" button, wondering what will happen when:
1. No "Live edit"
2. User changes a param in "Form" tab
3. Forgets to click "Sync"
4. Goes to "Changes" tab (no param updated)
5. Clicks "Deploy"
User will see the default value (not synced in "Changes"), but the one from "Form" will be applied?

What do you think about removing the sync button, and automatically doing the actual sync in both?: 
- click any other tab
- click "Deploy"

We could also try to leverage [Web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)?

**Comment by antgamdia** [comment]
Just sharing the current progress wrt the new table, will reply to the comment soon.

![Image](https://user-images.githubusercontent.com/11535726/189411443-38610fff-b361-4315-a8bc-e9d1be2c8b02.gif)

**Comment by castelblanque** [comment]
It is cool that there is a search option, great progress!
Did you discard the foldable sections (maybe lazy-loading)?

**Comment by antgamdia** [comment]
> I don't think we should put on the user's decision the result of a technical limitation (i.e. remembering to click "sync").


Neither do I: it was implemented like a manual action but just while developing. The underlying action is expected to be triggered automatically, for instance, always deferring the sync process to the moment when the user changes the tab.

> Is it sluggish always for all Yaml sizes? Could we behave differently in two scenarios (big and small yaml files?).

I have tested the "old" custom from (aka the bitnami one, just using a reduced subset of params) and it works perfectly. However, is when using the full schema (at least in the bitnami charts, as they are pretty configurable) that the lag appears.

> I'm a bit reluctant about having that "Sync" button, wondering what will happen when:

>No "Live edit"
>User changes a param in "Form" tab
>Forgets to click "Sync"
>Goes to "Changes" tab (no param updated)
>Clicks "Deploy"
>User will see the default value (not synced in "Changes"), but the one from "Form" will be applied?

Technically, it will appear a browser-native pop-up saying that you have unsaved changes. I was playing around with the `beforeunload` events. That said, I think we should try to avoid this use case.

> What do you think about removing the sync button, and automatically doing the actual sync in both?

100% agree


> We could also try to leverage [Web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)?

Good idea, not sure how can we use them along with the usual react's state typical management, but, for sure it is an interesting option to run such a lengthy operation like this one in bg. 


> Did you discard the foldable sections (maybe lazy-loading)?

Not at all! I just prioritized having a "working" table and just added a POC of the filters and pagination. Collapsible rows is something I wanna explore shortly.

**Comment by antgamdia** [comment]
More progress:



![Image](https://user-images.githubusercontent.com/11535726/190100128-6d37d0ec-0ac6-40a7-b958-37eee821bc92.gif)

**Comment by antgamdia** [comment]
Today's update:

After implementing the groping by parent property, I've sketched up the sync flow inside the component and "upstream" (to the parent's). I've tried to minimize the YAML parsing operations for perfornce and, instead, the table parms are updated locally.

The observed response times seem to be much better than before, so perhaps storing the modifications and applying them in batch when switching tabs is not that necessary. 
Reason? Now we're dealing with a nested array instead of a flattened one with hundreds of params.

Pending stuff from the top of my mind: 1) use the "deployed value", "default value from the schema", "default value from the values" properly; 2) improve the performance of the yaml editor; 3) improve the performance of the initial load (it takes several seconds)

![Image](https://user-images.githubusercontent.com/11535726/190222412-0d620391-7502-4b9e-bbf4-5bf307f496dc.gif)

**Comment by castelblanque** [comment]
Awesome, that looks always better!!

Some minor observations:
- Columnns change width when searching or paginating, probably adapting to the content. Shouldn't we use fixed size columns so that it looks more uniform?
- Clarity uses carets for marking folded/unfolded sections, e.g. [Tree views](https://clarity.design/documentation/tree-view).
- Have you considered using Clarity's [stack view with lazy loading for children](https://clarity.design/documentation/stack-view#lazy-loading-of-children)? Not sure if it is available for React, though.
- I guess "Deployed value" column shouldn't be visible for new deployments?

**Comment by ppbaena** [comment]
Awesome work @antgamdia !!! Looking forward for this table view available in Kubeapps 🚀

**Comment by antgamdia** [comment]
Sharing the progress with some gifs, but will describe the approach + reply to the comments soon. For now the quick summary is: I've removed the old ace text editor + react-diff component in favor of a single instance of a Monaco (aka vs code engine) diff editor. Since it uses webworkers under the hood, the overall performance is way better.

There are plenty of bugs and open issues in the current design, especially, some glitches when editing, since more deboucing is still required.

Current performance when using the biggest bitnami chart's values (thanos):
![newTable4Perf](https://user-images.githubusercontent.com/11535726/190802962-7700c9e3-a955-4421-adfd-87c6b41882a5.gif)

The editions in the table + diffEditor (+ real time feedback about what changed):
![newTable4Editor](https://user-images.githubusercontent.com/11535726/190802932-77da270f-6f07-436a-9988-c1843c427488.gif)

The diff view now allows choosing between diffing the deployed values or the package values (eg. a new version):
![newTable4Upgr](https://user-images.githubusercontent.com/11535726/190802982-00c2e958-24d0-499d-9eeb-8d2c776d136a.gif)


PS: I've been trying to add https://monaco-yaml.js.org/ (note the actual YAML validation against a json schema; it's awesome), but after some time dealing with webpack, I gave up (for now) since I wanted to have a fully working scenario today.

**Comment by castelblanque** [comment]
> webworkers under the hood

Happy to see that webworkers work as expected. It is a really good job!

Minor observation about UI from the last GIF: the switch that toggles the diff mode confused me a bit. It wasn't clear what was the state when the toggle was off (due to being off), and then the label changes when switching. What do you think about replacing that control with two radio buttons or a single dropdown?

**Comment by antgamdia** [comment]
I'll extract the TODOs into a separate issue, but, for the moment, let me quickly write them down here:

- Check if both js-yaml and YAML libraries are still required
- Check the custom basic form components feature with adopters:
  - For instance, render the custom components into a separate modal window.
- Missing renderers:
  - 1st level: object (at least, as array of tuples <string, any> for defining each property.
    - Currently falling back to a textarea.
  - array level: enum, arrays and objects
    - Currently falling back to a textarea.
- Add input validation based on the schema: there's some commented-out logic in the TextParam.tsx
- Allow searching params in nested values (currently just searching top-level params
