### ISSUE TITLE
Add static code analysis to CI

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4427]
### Description:

Adding static code analysis to Kubeapps code base, at least where possible (Go?, TS?)
[SonarQube/SonarCloud](https://sonarcloud.io/) could be a very good choice. SonarCloud is free for open source projects.

- Benefit: Adds continuous inspection, code coverage, code smells detection, code quality gates, etc.
- CI event: On PRs

Related to #4096

**Comment by antgamdia** [comment]
Just for the record, our colleagues in _sealed secrets_ added two interesting GH action:

- https://github.com/securego/gosec: Inspects source code for security problems by scanning the Go AST.

- https://github.com/golangci/golangci-lint: a collection of code linters for go. This issue is, in fact, tracked at https://github.com/vmware-tanzu/kubeapps/issues/3087

**Comment by antgamdia** [comment]
Closed by https://github.com/vmware-tanzu/kubeapps/pull/5045
