### ISSUE TITLE
OCI: self signed custom CA not working, not even with tlsInsecureSkipVerify

### ISSUE THREAD

**Issue by Morriz** [vmware-tanzu/kubeapps#4438]
Using the chart from v2.4.3 it is not possible to create an `AppRepository` with a self signed cert. Adding the ca via `spec.caCert` still gives:
```
x509: certificate signed by unknown authority
```

The CRD's spec also shows we can use `tlsInsecureSkipVerify` but that is not used in the chart, so I added it. However, that also does nothing. It seems as if OCI endpoints are not given the same treatment as ChartMuseum endpoint. Is `syncImage` `bitnami/kubeapps-asset-syncer:2.4.3-scratch-r2` not up to date?

**Comment by ppbaena** [comment]
From issue #515

**Comment by antgamdia** [comment]
Hi @Morriz , 

I have been looking a quick look at it, but haven't had a chance to fully reproduce it (I don't have a local chartmusseum handy now)
I created a new OCI repo from the UI (which has a checkbox to set the `tlsInsecureSkipVerify`) with a random self-signed CA and:

1) If not setting `tlsInsecureSkipVerify` I got an error since the chart index can't be downloaded, which is something expected, as the CA cert doesn't match at all.
2) When enabling the `tlsInsecureSkipVerify`, the OCI repo gets fetched like a charm. 

Also, at a glance, it seems we are passing the proper tls options back to the wire in both the OCI and Helm scenarios, have a look at: https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/asset-syncer/server/utils.go#L714.

Also, just for you to know, the OCI-related code we have is expected to change (see #4194, which depends on two Helm's PRs, one of them, aimed at adding the tlsInsecureSkipVerify for OCI natively in Helm). Perhaps we should also wait until we can just pass this tlsInsecureSkipVerify direcltly on the helm's side.

Is this problem still present in the latest kubeapps version? If so, can you give us a repoduceable example so that we can just replicate your environment and investigate the issue more quickly?

**Comment by Morriz** [comment]
I have not seen the custom CA being used by the client in kubeapps when connecting to an OCI repo, but I can try again soon. Tnx for your elaborate reply.

**Comment by ppbaena** [comment]
Hi @Morriz 👋 , do you have time to check for it? Do you have any update here? Thanks!
