### ISSUE TITLE
Use grpc-web gateway to map status grpc codes to http codes

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4544]
### Description:

It would be less error-prone to return proper http codes on grpc failing requests, if possible.

Currently the http code is always 200, and the error data is in returned headers `grpc-*`.

![image](https://user-images.githubusercontent.com/67455978/161072164-83dc4224-de2f-4712-acad-89204e7eda7c.png)

According to [grpc-web documentation](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#http-status-code-mapping):

>  grpc-web gateway is recommended to overwrite the default 200 status code and map any gateway-generated or server-generated error status to standard HTTP status codes (such as 503) when it is possible.

**Comment by absoludity** [comment]
I'm not sure what that sentence is trying to say, in that grpc-web is a specification for a protocol for use in browsers that [specifies that the status is encoded in http/1 headers as key-value pairs](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) (see message framing). 

Can you link to an example of a grpc-web gateway that would do that translation other than the `grpc-gateway` that we already provide (but don't use ourselves)? I'm wondering if it's talking about something like grpc-gateway that provides http responses in a rest-like API (with those error codes), rather than using the grpc-web protocol, as I don't see how it could mean grpc-web protocol itself getting responses with the overwritten status codes.

Keen to understand.

**Comment by castelblanque** [comment]
>I'm wondering if it's talking about something like grpc-gateway that provides http responses in a rest-like API

Yeah, something like that. Except that not REST related, but just setting http status codes accordingly and leaving the `grpc-*` headers.

Idea behind it was, from a developer point of view at least, to avoid the misleading `200 OK` for grpc-web requests, when sometimes those requests failed and have the headers `grpc-message,grpc-status`. Also for Kubeapps users not familiar with grpc protocol, seeing `200 OK` in browser network request might be confusing.
It is not a functional problem, just related to human interaction probably.

Not that I had a clear design on how to implement something like this. I wondered if having some kind of piece in the backend that would set the right http status from the grpc status header (when possible) would work. E.g. `grpc-status: 5` to http response status `404`, but not meaning to remove `grpc-*` headers.
Maybe this might break the behavior of the JS/TS of grpc-web, and it is not worth the effort?

FYI Someone asked for a similar thing in Envoy [here](https://github.com/envoyproxy/envoy/issues/5331).

**Comment by absoludity** [comment]
Yeah, I don't think we could do a change like that on the server since it'd break the grpc-web protocol. On the client (as per the last comment in the envoy question to which you linked), the grpc-web client handles the response and raises errors etc. based on the response correctly.

The main issue I think you're raising is that debugging for users can get a bit tricky, right? To which I'd answer, yes - it can (at least, I've had to explain why I'm asking for a screenshot of a 200 response a couple of times :) ).

I think this just comes down to using gRPC which uses http2 trailers to send the status (at the end of a response). For example, the [grpc http2 protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) outlines that:

>  If Content-Type does not begin with "application/grpc", gRPC servers SHOULD respond with HTTP status of 415 (Unsupported Media Type). This will prevent other HTTP/2 clients from interpreting a gRPC error response, which uses status 200 (OK), as successful.

so yep, if we're asking people to help debug grpc-web requests that were intended for a grpc-web client, it'll just require a little more education than usual.
