### ISSUE TITLE
helm repo with empty index throws error

### ISSUE THREAD

**Issue by Morriz** [vmware-tanzu/kubeapps#4611]
### Description:

An empty `helm` chart repo is queried by the `apprepo-kubeapps-sync` job which then errors. I believe it should just report "No charts found."

### Steps to reproduce the issue:

1. add a chart repo with no charts in it
2. observe job erroring: `apprepo-kubeapps-sync-$name-...`

**Comment by absoludity** [comment]
Yep, that'd be nicer. I'll tag this as a good first issue type. Happy to help anyone who would like to do this change.

**Comment by gfichtenholt** [comment]
looks similar to https://github.com/vmware-tanzu/kubeapps/issues/2962

**Comment by absoludity** [comment]
> looks similar to #2962

Yeah, that one was solved by improving the validation to check the OCI repo before allowing the user to add it. We could do a similar improvement to the validation for adding a helm repo here (ie. provide feedback in the UI to stop you adding an empty helm repo).

But I thought this issue was just about the error seen in the sync logs itself... rather than just displaying "No charts found"?
