### ISSUE TITLE
[carvel] Address upcoming change in the `-ctrl` ConfigMap suffix (kapp >=0.47)

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#4672]
We were told (thanks Scott!!) that Kapp is going to change the naming convention of the ConfigMap from which we fetch the generated k8s resources by an App.

We have to:

- Analyze the implications of the change in ~https://github.com/vmware-tanzu/carvel-kapp/issues/146~ https://github.com/vmware-tanzu/carvel-kapp-controller/issues/376
    - Slack thread discussing this change: https://kubernetes.slack.com/archives/CH8KCCKA5/p1652136784883199 
- Come up with a solution ensuring backward compatibility

**Comment by neil-hickey** [comment]
hello! The issue you referenced won't be the naming convention for the short term in Kapp-controller. Instead we are following this issue: 

https://github.com/vmware-tanzu/carvel-kapp-controller/issues/376

The naming convention will go from `my-pkgr-name-ctrl` to `my-pkgr-name.pkgr` and other types (AppCR / PKGinstall) will be `.app` instead of `-ctrl`.

Hopefully this provides a little more context.
