### ISSUE TITLE
Operators e2e test randomly failing

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4832]
**Describe the bug**
Lately some e2e tests runs fail due to failure in

`tests/operators/06-operator-deployment.spec.js:8:1 › Deploys an Operator`

**To Reproduce**

Hard to reproduce, it happens some times e.g. [this CI run](https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/7398/workflows/e1a32fa9-7d4f-4b70-80a5-2bd3c78e1648/jobs/85652).

**Expected behavior**
E2E tests run smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/67455978/171872144-a163cec2-4f85-4077-9428-9694ac6c4015.png)

**Comment by dlaloue-vmware** [comment]
The issue is not fixed, as i had more than 5 failed run in a row on 2 different changes: e.g. https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/7484/workflows/53ebeea6-5d27-4712-b645-5d2fb3185842/jobs/86399

The code that makes the test fail is the following line of code that was changed:
      await page.waitForTimeout(utils.getDeploymentTimeout());
The waitForTimeout is in fact a sleep, so it will wait for the entire duration of the deployment timeout value.

The reason why this change made the test fail consistently instead of intermittently is that in all the failure cases, the "deployment timeout" ends up being "86" instead of the expected "2". And so the waitFortimeout waits for 86mn but times out at the test timeout (6mn).

I was able to trace this value "86" as being half of 172, which is the beginning of the additional cluster ip address 172.18.0.3.

so for some unknown reason yet, when CI executes the test, there are times where the environment is corrupted and not all variables are properly passed in.
The TEST_TIMEOUT_MINUTES variable ends being 172.18.03, which will lead to a deployment timeout of 86.

I am still trying to trace back to why the environment is not properly set

**Comment by dlaloue-vmware** [comment]
failed test showing the deployment timeout:
<img width="959" alt="e2e fail" src="https://user-images.githubusercontent.com/74025858/172540743-c2c19cf9-8381-4e44-bf72-7672b1ef41b5.png">

successful test, deployment timeout at 2mn:
<img width="953" alt="e2e success" src="https://user-images.githubusercontent.com/74025858/172540836-27fc5e00-5e49-495b-ab47-fd487357c4ce.png">

screenshot showing the environment for failed case:
![e2e fail env](https://user-images.githubusercontent.com/74025858/172541114-e1f24f05-929f-4322-9e26-73c30980389b.png)

**Comment by castelblanque** [comment]
Thanks for the investigation Dimitri.
Even when we fix the correct timeout number, we might run into the same issue as before adjusting that line of code.

So we have two issues here:
- Wrong parameters being passed to E2E tests at some points
- Operators E2E test randomly failing

**Comment by dlaloue-vmware** [comment]
the problem happened again: https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/7570/workflows/5c3c68af-e882-4651-971c-be412aa1ad6b/jobs/87268/steps
the timeout was set as 172.

**Comment by dlaloue-vmware** [comment]
As Rafa found out, some variables are not set (especially the sensitive data ones) and this causes values to be assigned to the wrong variables.
The following commit https://github.com/vmware-tanzu/kubeapps/commit/223a2339cff7c5260918e63f1aba666c75838047 provides a temporary fix by reordering the variables so the ones without value are listed last.

**Comment by castelblanque** [comment]
Thanks @dlaloue-vmware . I'm working on #4910 that will allow us to get rid of the `DOCKER_*` parameters, the only ones actually needed by the E2E script.
I see that #4903 has been merged so I'll continue from there.
