### ISSUE TITLE
"Show all apps" for lesser priviledged users + Namespace blacklisting 

### ISSUE THREAD

**Issue by smerschjohann** [vmware-tanzu/kubeapps#4921]
**Summary**
Currently the namespace and list all chart feature is supoptimal for lesser priviledged users on the cluster

**Background and rationale**

Currently it is not possible to manage the visible namespaces a user can see, except of the use of RBAC. Either one sees all repositories as they have the permission to list all namespaces or you add a service account with the list right, don't give it to the users where a custom kubeapps feature kicks in which lists only namespaces where the user can list secrets. But the latter reduces the rights of the user in such a way, that `helm ls -A` does not work, as it only makes sense in scenarios where the user will not be able to list secrets in all namespaces. But the current implementation of the "list all installed apps" feature relies on this helm implementation, which renders that feature only usable for cluster priviledged users.

Or in other words: only users with a ClusterRoleBinding of admin or similiar can have an overview of all installed charts in all namespaces they have access to. The "normal" users have to click through each namespace individually.

**Description**
So instead of relying on the in buildin `helm ls -A` feature, the namespace listing pattern should be adopted to list all apps where a user has permissions to. 

Furthermore, but with a slightly different "agenda" it would be nice to filter some namespaces completly by some label selector. This would allow to exclude some "cluster managed" namespaces from cluttering the app list and namespace list

**Acceptance criteria**
It is possible to use the "list all apps feature" for restriced users as well. They should see the apps of namespaces they have access to.
Furthermore it should be possible to blacklist some namespaces from being visible in kubeapps, even if the user has access to it. It would be enough if this blacklist applies to all users.

**Comment by absoludity** [comment]
Hi @smerschjohann . Thanks for the thought that you've put into improving things here!

Let me ask some questions in-line here, to see if I've understood as well as clarify some existing behaviour.

> Currently it is not possible to manage the visible namespaces a user can see, except of the use of RBAC.

That's correct: currently we only show the namespaces to which users have access.via RBAC. I assume you don't mean that we show namespaces to which the user does not have access, but rather that we could help show only a subset of namespaces to which they have access?

> Either one sees all repositories as they have the permission to list all namespaces or you add a service account with the list right, don't give it to the users where a custom kubeapps feature kicks in which lists only namespaces where the user can list secrets. But the latter reduces the rights of the user in such a way, that `helm ls -A` does not work, as it only makes sense in scenarios where the user will not be able to list secrets in all namespaces.

The last sentence confused me: I don't think we're reducing the rights of the user, we're enabling the user to list all the namespaces to which they have access (something which vanilla kubernetes and hence helm `helm` don't provide, although some distributions such as OpenShift do provide this). And Kubeapps only uses this functionality when the user's own RBAC does not allow them to list namespaces (from memory, otherwise it just uses the user's token).

> But the current implementation of the "list all installed apps" feature relies on this helm implementation, which renders that feature only usable for cluster priviledged users.

That should not be the case, and is a bug if so - perhaps introduced in the churn of switching to the new API service. I'll need to verify locally (but just found that locally I can't get past the login with my non-privileged user as the returned namespaces is empty). We'll look into this as the issue. Thanks!

**Comment by smerschjohann** [comment]
> that's correct: currently we only show the namespaces to which users have access.via RBAC. I assume you don't mean that we show namespaces to which the user does not have access, but rather that we could help show only a subset of namespaces to which they have access?

Yes, correct. As you already saw I extracted that part to a seperate issue. As that is not the main part of this particular issue.

> The last sentence confused me: I don't think we're reducing the rights of the user, we're enabling the user to list all the namespaces to which they have access (something which vanilla kubernetes and hence helm helm don't provide, although some distributions such as OpenShift do provide this). And Kubeapps only uses this functionality when the user's own RBAC does not allow them to list namespaces (from memory, otherwise it just uses the user's token).

Ok, I formulated it in a bad way, sorry for that. What I meant: It makes sense to iterate through the namespaces to see if the user has access by the secrets technique. Kubeapps itself does not reduce anything, of course. What I meant here is, that the current frontend and backend code checks if the user can list secrets in ALL namespaces, so the `kubectl get secrets -A` or `helm ls -A` feature. 
But since the motivation was to reduce the users rights, they won't have that right, that won't make any sense from a permission perspective. The frontend checks it here: https://github.com/vmware-tanzu/kubeapps/blob/23e9605572081810df0f481d5a2188867a307a47/dashboard/src/components/AppList/AppList.tsx#L84

> That should not be the case, and is a bug if so - perhaps introduced in the churn of switching to the new API service. I'll need to verify locally (but just found that locally I can't get past the login with my non-privileged user as the returned namespaces is empty). We'll look into this as the issue. Thanks!

I don't mean the dropdown namespace list, I explicitly mean the "list all apps" feature.

In the new implementation it is not implemented: https://github.com/vmware-tanzu/kubeapps/blob/3566a746abed6d13a702fafb4a4c6c8f4607fd82/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go#L184

In the current implementation, it uses the normal `helm ls -A` feature, that relies to list all secrets: https://github.com/vmware-tanzu/kubeapps/blob/1099a5066422b0befe1c01814cabe7b0b756fe66/pkg/agent/agent.go#L59

**Comment by absoludity** [comment]
Right, got it - I think :) And furthermore, now re-reading your original description makes perfect sense. Thanks. So, down to the details: I think it is actually implemented the same way in the new implementation... the code you linked to is for the `GetAvailablePackageSummaries` where we don't allow this across namespaces, but if you check the implementation of `GetInstalledPackageSummaries`:

https://github.com/vmware-tanzu/kubeapps/blob/3566a746abed6d13a702fafb4a4c6c8f4607fd82/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go#L453

you'll see it's setting the same flag for `cmd.AllNamespaces = true` as the previous implementation, so no change there.

Whereas the feature you're asking for is, I think, that the "All namespaces" switch changes semantics slightly to be "All namespaces that I can access", and so you could see the installed applications across all namespaces to which you have access with the switch being visible always (or if a user has access to more than one).
We'd have to think about the implications of this, since I think the backend would need to do N separate requests for N namespaces (in a similar way that the aggregated API does N per N plugins).

**Comment by smerschjohann** [comment]
Yes the backend has to do that. Another way would be to allow the serviceaccount not only namespace, but also secret permissions - but not a good idea.

But I'm not sure how bad it is, of course, if the user has a lot of namespaces, it will become noticable. On the other side `kubectl` itself does a lot of requests (for crds, api resources, ...) as well, so it should not matter much.
But to reduce that impact, a pagination could be introduced. List the apps of the first N namespaces (ordered list of namespaces required), ...

**Comment by absoludity** [comment]
> Yes the backend has to do that. Another way would be to allow the serviceaccount not only namespace, but also secret permissions - but not a good idea.

Right, not something I'd want to consider. Yes, we could use a service account with access to all namespaces and filter the results, but we'd be working against the k8s security. I'd rather aim to build things that work *within* the provided k8s security model.

> But I'm not sure how bad it is, of course, if the user has a lot of namespaces, it will become noticable.

It would mean that for every request for a page of results, we'd need to (1) check all namespaces to see which namespaces the user can access, and then (2) request apps in each of those namespaces individually (or it could possibly be done just with (2) by just trying each namespace with the users creds), which is potentially hitting the cluster for each plugin, then ordering the results for pagination (as we do for the plugins).

> On the other side `kubectl` itself does a lot of requests (for crds, api resources, ...) as well, so it should not matter much.

I don't think we can afford that argument :) `kubectl` does lots of requests in certain situations, but that doesn't therefore give us the freedom to add functionality that will also require lots of requests.

> But to reduce that impact, a pagination could be introduced. List the apps of the first N namespaces (ordered list of namespaces required), ...

Yeah, that would be a good way to reduce the impact (paginating by namespace, that is), but the order (alpha-per-namespace?) would be inconsistent with user expectations and current behavior in Kubapps, kubernetes and helm (alpha ordering across complete result). It already took quite a bit of work to get the consistent ordering performant with pagination across multiple plugins (see fan-out, [fan-in with golang channels](https://liveandletlearn.net/post/fan-out-fan-in-golang-kubeapps/)). We could potentially implement something similar for app across namespaces, but it'd be a very heavy request (across plugins then across namespaces)

Unfortunately, until `kubectl` (and the k8s API) allows something like `kubectl get po --all-namespaces-to-which-I-have-access`, I don't think the benefit will outweigh the cost  :/

OpenShift used to provide `project`s as collection of namespaces, but they appear to have moved that concept to be more inline with Kubernetes now (a project in Openshift is now just a namespace with special annotations). [Rancher "Projects"](https://docs.ranchermanager.rancher.io/pages-for-subheaders/manage-projects) are like groups of namespaces, but even that doesn't allow fetching resources across a project (afaict).

While researching here, I was excited to find Kubernetes support for [Hierarchical namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces/tree/master/docs/user-guide), which are providing something akin to Rancher projects. Hierarchical namespaces could solve part of the problem ("Which namespaces can I access" - if Kubeapps somehow limited a user to a hierarchy), but it still doesn't solve "Let me list all resources in the namespaces to which I have access" (ie. there's no support for listing resources across all namespaces in a hierarchy). I've created an [issue to track listing resources across a hierarchy](https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/235) in case there are other thoughts by the authors there.

I'll close this issue for now, until the kubernetes support is closer to the requirement here, though I'd be keen to re-open it if such queries do become supported by hierarchical namespaces or similar.
