### ISSUE TITLE
Create Namespace: add static labels to namespace

### ISSUE THREAD

**Issue by smerschjohann** [vmware-tanzu/kubeapps#4922]
**Summary**
Kubeapps allows to add namespaces to the cluster by the "create namespace" button. It should be possible to add static additional labels added to those newly created namespaces

**Background and rationale**
Currently the created namespaces by Kubeapps do not have any specific labels. But those labels would allow different Kubernetes components/operators/policy controllers to apply certain behavior. Like adding RoleBindings, NetworkPolicies, ... Currently that's only possible by either applying it to all newly created namespaces or figuring out through the initator with some rather complex logic.

**Description**
With these (static but configurable) labels it would even be possible to create a kubeapps with only "managed by kubeapps" namespaces. For that the namespaces could be filtered with a whitelisting label selector. In the other ticket I created earlier (#4921), I talked about a blacklist, to filter out certain namespaces. For the usecases I have in mind, it would work even better with such a whitelisting approach.

**Acceptance criteria**
Newly created namespaces are labeled with a preconfigured label.

**Comment by absoludity** [comment]
So this would be a configuration setting of the Kubeapps chart (rather than a UI field or similar)? To maintain the existing behaviour, the new config option could default to an empty string "", so that all namespaces (to which a user has access) are displayed and no label is added to new namespaces. If the config is updated to "some-label", then users would only see the subset of namespaces to which they have access which also have this label. Similarly when a new namespaces is created, it'd be created with the label. Have I understood correctly?

**Comment by smerschjohann** [comment]
Yes, that would be great. And yes it can be as static as that.

But I would keep the configuration seperate. Something like:

```
createNamespaceLabels:
    managed-by: kubeapps 
visibilityFilters:
   include:
    - type: nsSelector
      value: "managed-by=kubeapps"
```

**Comment by smerschjohann** [comment]
I would jump on this one, if you want to.

**Comment by absoludity** [comment]
> I would jump on this one, if you want to.

Excellent, yeah, that'd be great @smerschjohann .

**Comment by ppbaena** [comment]
That would be great @smerschjohann! Thanks for your contribution.
Don't know if following us in the [#Kubeapps channel](https://kubernetes.slack.com/messages/kubeapps) on the Kubernetes Slack server, so you can keep posted on Kubeapps news, releases and other discussions.
