### ISSUE TITLE
Release 2.4.6: Create a release once we finish the API for helm + remove assetsvc workaround in cobra

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#4936]
See https://github.com/vmware-tanzu/kubeapps/pull/4880#discussion_r893598038

**Comment by antgamdia** [comment]
Blocked until we finish #4757

**Comment by antgamdia** [comment]
The release is in progress, but, as it requires some small changes on the Bitnami side (we changed the "App Repo" with "Package Repo", so some E2E tests are failing), the official container images will take a little bit more time in being released.

**Comment by antgamdia** [comment]
Quick update: the v2.4.6 container images were already released ([example](https://hub.docker.com/layers/kubeapps-apis/bitnami/kubeapps-apis/2.4.6-debian-11-r1/images/sha256-030eb7b3baf2739ae2604db6e1f77ed3e3a535b42cadc9002b33df00e2584b18?context=explore)), however, due to some minor issues on their side, the chart is not released yet. We hope to get it sorted out soon.

**Comment by ppbaena** [comment]
Move to in review after those minor issues are solved.
