### ISSUE TITLE
Analyze Kubeapps capabilities (and differences) on multi-cluster vs single cluster

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5145]
**Summary**
Analyze Kubeapps capabilities (and differences) when running on multi-cluster vs Kubeapps running on a single cluster

**Background and rationale**
It is possible to configure Kubeapps to target other clusters when deploying a chart, in addition to the cluster on which Kubeapps is itself deployed. In order to improve the multi-cluster experience it is necessary to analyze the existing differences when running Kubeapps on a multi-cluster configuration VS single cluster configuration.

**Description**
A clear and concise description of what you want to happen, including all scenarios.

**Acceptance criteria**

- [ ] List Kubeapps capabilities and features for single cluster and multi-cluster configuration
- [ ] Identify gaps and differences between these two configurations
- [ ] Identify scenarios and actions to be performed to fill identified gaps

**Comment by castelblanque** [comment]
Some issues found during the investigation:

- Listing (available/install) packages summary from additional cluster leads to error if just one of the plugins fails to deliver (e.g. Carvel not supporting anything on additional clusters).
- Kubeapps claims that has multicluster support at least for Helm and global repos, but if a package to be installed in additional cluster needs `imagePullSecrets` for retrieving container images, it won’t work even in the claimed scenario. Those secrets are not copied to additional cluster.
- When additional clusters are not reachable (due to invalid OIDC, network issue, etc) clearly show a message in UI (e.g. in the “switch context” dialog). Currently “namespace” dropdown appears empty (retrieving namespaces is the first operation done when an additional cluster is selected)

All of the above should be tackled in the new [Design for extending Multicluster functionality](https://github.com/vmware-tanzu/kubeapps/issues/5152).
