### ISSUE TITLE
Listing all repositories an unpriviledged users can access to

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5215]
**Summary**
When using non-admin RBACs, the Apprepos `List` over the whole cluster action requires a ClusterRole (since we are passing `""` namespace). However, we should still be able to identify which ns a users has access to and then, list repos for each one.

**Background and rationale**
Otherwise, the current behavior is returning an empty set of repos, which could be misleading for the users.

**Description**

See above. 

**Acceptance criteria**

- Unprivileged users are able to fetch all the repositories from the namespaces they have access to.

**Additional context**
An issue related to this problem was solved at https://github.com/vmware-tanzu/kubeapps/pull/5207

**Comment by castelblanque** [comment]
Scenario is when a user only has access to a specific set of namespaces (e.g. `kubeapps-user-namespace`), and does not have permissions to list namespaces.

1. When user performs `GetPackageRepositorySummaries` passing as context the `cluster` and `namespace: kubeapps-user-namespace` -> Gets a valid list of accesible repositories in that namespace
2. When user performs `GetPackageRepositorySummaries` passing as context the `cluster` and no namespace (or `namespace: ""`) -> Gets error `Forbidden to get the AppRepository 'all' due to...`

The latter should return the same list as the former, and not an error.

**Comment by castelblanque** [comment]
Implementation-wise this brings a considerable change. Internally, when we handle the aforementioned error, we need to then find out the list of namespaces that the user has access to.
It turns out that we already have that logic [here](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go#L80), but it is under the `resources` plugin. And plugins with the repositories API do not have access to the resources plugin.

This will involve moving the logic from the resources plugin to somewhere under `/pkg` so that it is available to all plugins.

**Comment by castelblanque** [comment]
Work for Helm plugin is done in #5453.
For Fluxv2 plugin it is already checking if the user has actual access to the namespace.
For Carvel, same work as in Helm plugin needs to be done.
