### ISSUE TITLE
Unable to use Flux OCI with Harbor robot accounts

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5219]
**Summary**
I've been adding minor changes for the UI to also support the OCI registries with Flux (PR #5218), in doing so, I'm kind of unable to add one (harbor) and get the packages.

**Background and rationale**

It's important as in many Harbor deployments we don't have full admin access, but maybe admin permissions over a single project (not the whole harbor instance). Using robot accounts seems to be the preferred way to consume TAC/VAC, therefore, I guess it's important that we also support this way to enable VAC users to deploy their apps using kubeapps+flux.

**Description**

In the logs I see:

```
ORAS .Repositories() returned err: GET "https://harbor-repo.vmware.com/v2/_catalog?last=agamez": unexpected status code 401: unauthorized: unauthorized to list catalog: unauthorized to list catalog
```

I assume that this is because the robot accounts are not privileged enough (see https://github.com/goharbor/harbor/issues/8723#issuecomment-730248740).

However, the following endpoint seems to work with robot accounts and does give me the list of artifacts inside the project I have access to: `https://harbor-repo.vmware.com/api/v2.0/projects/agamez/repositories`

**Acceptance criteria**

- The Flux OCI support works with robot accounts.

**Additional context**

N/A

**Comment by gfichtenholt** [comment]
I am able to use robot accounts with demo.goharbor.io without any issues. A PR with an integration test to that effect is pending https://github.com/vmware-tanzu/kubeapps/pull/5246/files#

**Comment by gfichtenholt** [comment]
please feel free to re-open as you see fit

**Comment by gfichtenholt** [comment]
Reopening due to:
If I run a test that uses admin account followed by a test that uses a robot account everything runs fine. If I then bounce the kubeapps apis pod and run only the test that uses a robot account that fails. So I think there are a couple of issues:

1. there is some stale in-memory cached state (maybe in ORAS libs) that is set up by one test and somehow affects other tests.
2. There is some likelihood the robot account never worked with kubeapps. To fix it:
  a. We can pursue ppl behind harbor to see if it is possible to use standard API with robot accounts via some server-side config settings OR
  b.  might have to introduce a vendor-specific repository-lister
