### ISSUE TITLE
carvel repository UI: several issues with carvel support in creation dialog

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#5244]
I did some tests of the new repository creation dialog UI, and i found a couple issues for carvel support:
 - the "inline" type is not supported and should not be listed (or greyed out) for creation
 - the auth options are enabled regardless of the type when they are type specific (for example SSH is only supported by GIT type, HTTP only supports basic auth...)
 - in the advanced section, only the duration is supported, the other fields should be removed

for duration, the description says it is "goland" format. I don't thin this should be described that way, instead it is the time/unit duration format supported by the k8s api spec (it does not really matter whether they modeled it after goland or not).

**Comment by antgamdia** [comment]
Thanks for reporting it. I have a couple of questions:
> the "inline" type is not supported and should not be listed (or greyed out) for creation

I'm ok with disabling it, but it seems there is code handling this type, isn't there? See: 

https://github.com/vmware-tanzu/kubeapps/blob/79c7acd58dadb94415e9c49affe3b5432fee5b9b/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go#L397

> the auth options are enabled regardless of the type when they are type specific (for example SSH is only supported by GIT type, HTTP only supports basic auth...)

Again, it seems we are accepting each auth type in the code, no? See

https://github.com/vmware-tanzu/kubeapps/blob/79c7acd58dadb94415e9c49affe3b5432fee5b9b/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go#L551-L586

However, I've been able to find this info at https://github.com/vmware-tanzu/carvel-kapp-controller/blob/v0.40.0/pkg/apis/kappctrl/v1alpha1/types_fetch.go. Perhaps the API should also honor this subset of available types?


> (...) instead it is the time/unit duration format supported by the k8s api spec

Do you have a link that says which is this k8s API spec so that we can refer our users to it? I only was able to find info like "k8s uses the go duration format", but nothing else.

**Comment by antgamdia** [comment]
Fixed at https://github.com/vmware-tanzu/kubeapps/pull/5248
