### ISSUE TITLE
[Discussion/Concept] Dashboard: Wouldn't it better to directly talk with K8s API where feasible?

### ISSUE THREAD

**Issue by dionysius** [vmware-tanzu/kubeapps#5452]
**Summary**
The dashboard talks to the k8s api [using the go grpc backend](https://github.com/vmware-tanzu/kubeapps/blob/c4d25a4151fd1b5c9c86fe4ecd2b41abf33e9317/dashboard/src/shared/KubeappsGrpcClient.ts#L72). The requests made to the k8s api don't need further manipulation from the go backend, except it impersonates the user and sends the request to the k8s api.

**Background and rationale**
Why using a go grpc backend middleman for those requests, since the [nginx is configured to offer a location to talk to the k8s api directly](https://github.com/vmware-tanzu/kubeapps/blob/c4d25a4151fd1b5c9c86fe4ecd2b41abf33e9317/chart/kubeapps/templates/frontend/configmap.yaml#L72). We could remove all code related to this interaction in the middleman and also (IMO) make the interaction with the k8s api much simpler and easier if there would be a real k8s api client available.

**Description**
I believe the go grpc middleman grew because there was (and still is) no official k8s client for use in a web frontend (there are plenty for node). But we can generate such one with help of the openapi spec of the k8s api.

Pro: We also have fully typed objects and original k8s api status codes this way. Con: Those types are not small and will need to be included in the webpack build, which makes the js part bigger. But we also save the resource messages and types in the grpc spec. Hint: This is why I only imported specific apis and models to keep the import tree minimal.

**Acceptance criteria**
TBD (unsure how auth proxy and oauth interfere with this)

**Additional context**
Overall there is a branch in my fork as PoC: [full diff but cluttered with generated files](https://github.com/dionysius/kubeapps/compare/main...poc-openapi-client). Have a look especially at
- [Auth.ts](https://github.com/dionysius/kubeapps/compare/main...poc-openapi-client#diff-d3542521e82251ef63d47d690cc9d3916545d48c0c4311a1f2e06f7eeb4a71bb)
- [Kube.ts](https://github.com/dionysius/kubeapps/compare/main...poc-openapi-client#diff-dfba08c272abc14a54ae2ce42c7b3efbf616ba1676da30fb1b3c286fe1d85c36)

1) Generating the k8s api client using openapi-generator ([configured to use axios](https://github.com/dionysius/kubeapps/blob/poc-openapi-client/dashboard/openapi-gen.config.yaml#L4))

```
# in a separate terminal
$ export KUBECONFIG=~/.kube/k3s-os.config
$ kubectl proxy --port=8080
Starting to serve on 127.0.0.1:8080
```
```
# in a separate terminal
$ yarn gen-k8s-client
yarn run v1.22.19
  openapi-generator-cli generate -c ./openapi-gen.config.yaml
...
[main] INFO  o.o.codegen.TemplateManager - writing file src/gen/k8s-client/models/io-k8s-api-core-v1-service.ts
...
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
Done in 17.85s.
```
-> We have the full k8s api available in that client

2) Use that generated code to better interact with the k8s api. E.g.

Instead of
```
  public static async canI(
    cluster: string,
    group: string,
    resource: string,
    verb: string,
    namespace: string,
  ) {
    try {
      if (!cluster) {
        return false;
      }
      // TODO(rcastelblanq) Migrate the CanI endpoint to a proper RBAC/Auth plugin
      const response = await this.resourcesServiceClient().CanI({
        context: { cluster, namespace },
        group: group,
        resource: resource,
        verb: verb,
      });
      return response ? response.allowed : false;
    } catch (e: any) {
      return false;
    }
  }
```
we can do
```
import { AuthorizationV1Api as AuthorizationApi } from "gen/k8s-client/apis/authorization-v1-api";

  public static async canI(
    cluster: string,
    group: string,
    resource: string,
    verb: string,
    namespace: string,
  ): Promise<boolean> {
    try {
      if (!cluster) {
        return false;
      }
      const authApi = new AuthorizationApi(undefined, url.api.k8s.base(cluster), axiosWithAuth);
      const resp = await authApi.createAuthorizationV1SelfSubjectAccessReview({
        spec: {
          resourceAttributes: {
            group: group,
            namespace: namespace,
            resource: resource,
            verb: verb,
          },
        },
      });
      return resp.data.status?.allowed || false;
    } catch (e: any) {
      console.log("canI failed:", e);
      return false;
    }
  }
```
(Ignore my very minimal error handling, its a PoC for discussion.)
-> we can omit the `resourcesServiceClient` middleman

For sure it would be advisable to also simplify the initialisation of the different (sub)API's in a shared location. I think this one is generator related with axios.

3) Finally get rid of all code in the backend related to "just" talking with k8s as impersonated user

**Comment by absoludity** [comment]
Hi there @dionysius . Sounds like a fun experiment and a neat tool for creating JS clients of certain K8s APIs!

> **Summary** The dashboard talks to the k8s api [using the go grpc backend](https://github.com/vmware-tanzu/kubeapps/blob/c4d25a4151fd1b5c9c86fe4ecd2b41abf33e9317/dashboard/src/shared/KubeappsGrpcClient.ts#L72). The requests made to the k8s api don't need further manipulation from the go backend, except it impersonates the user and sends the request to the k8s api.

The main reason is that installing Kubeapps should not implicitly expose your Kubernetes API with a frontend that will proxy requests directly to the Kubernetes API. In the past Kubeapps did exactly that: if you have a Kubernetes cluster that is not exposed to the internet (ie. you can use `kubectl` to talk to it only through your VPN or through a jump-host), and you installed Kubeapps with the frontend exposed outside your private network, then Kubeapps would have been implicitly exposing your cluster's Kubernetes API server to the world. This was a long-running security risk that we ensured people were aware of, but nonetheless were keen to fix. The Kubeapps API service (which is available in both gRPC and http) exposes only the functionality that Kubeapps requires ("what packages are available to install", "what packages are installed" etc.), rather than all API endpoints of the cluster's API server.

The second reason is that Kubeapps shouldn't be coupled directly with Helm: for the future of the project, both people in the community and the team were keen to ensure that Kubeapps remained relevant regardless of the packaging system used. If the dashboard is talking directly with the K8s API server, then for each type of package (Helm, Carvel, operator, etc.) the dashboard would need to run *different* code and be updated with each packaging format, and querying for all installed packages regardless of format would require complexity that should not be in the dashboard frontend application. So when designing the small number of messages required by our dashboard for the first and most important reason above, we saw an opportunity to create a pluggable API server that handles queries like "what packages are available for install" and returns those packages for all installed plugins to the dashboard. This way, the dashboard can focus on presenting those results to the user, while the backend api server handles the complexity of marshaling the results from different packaging systems into a response etc.

Hope that makes sense, I'll provide a few more bits of detail below inline. 

> 
> **Background and rationale** Why using a go grpc backend middleman for those requests, since the [nginx is configured to offer a location to talk to the k8s api directly](https://github.com/vmware-tanzu/kubeapps/blob/c4d25a4151fd1b5c9c86fe4ecd2b41abf33e9317/chart/kubeapps/templates/frontend/configmap.yaml#L72). 

If you check a few lines up (L65), you'll see that this is only the case if the `operators` feature flag is on. Ideally we'd replace the existing operators support (which talks directly to the cluster) with a plugin, as we have already done so for the helm, carvel and flux support, but it's not yet been a priority. So currently yes, nginx is configured to offer a location to talk to the k8s api directly **only when the operator support is enabled**, otherwise Kubeapps does *not* expose your Kubernetes API server.

> We could remove all code related to this interaction in the middleman and also (IMO) make the interaction with the k8s api much simpler and easier if there would be a real k8s api client available.

It would be simpler if we only supported one packaging format, such as Helm, as we used to do. But when supporting multiple packaging formats, it very quickly puts a large burden of complexity on the dashboard, with different code for different packaging formats, marshaling results together etc. (the existing operator support is an example of this). This is in addition to the fact that it would expose the K8s API server (which in some cases, where it's exposed already, may not be an issue, but should not be a general assumption, IMO).

> 
> **Description** I believe the go grpc middleman grew because there was (and still is) no official k8s client for use in a web frontend (there are plenty for node). But we can generate such one with help of the openapi spec of the k8s api.

No - this was not why the kubeapps-apis service grew, as outlined above (and note, it speaks both gRPC and HTTP)

> 
> Pro: We also have fully typed objects and original k8s api status codes this way. Con: Those types are not small and will need to be included in the webpack build, which makes the js part bigger. But we also save the resource messages and types in the grpc spec. Hint: This is why I only imported specific apis and models to keep the import tree minimal.

Yeah - you're right in that, if it was OK to always expose the K8s API server and we continued to support one package type only, this would be a really cool way of creating a client rather than using the HTTP API for the k8s API server directly. Neat!

> 
>     3. Finally get rid of all code in the backend related to "just" talking with k8s as impersonated user

Note that we don't impersonate (in the sense of using an impersonation API with some other credentials): When installed with the auth-proxy (as we recommend) the dashboard, like any web application, just ends up with an encrypted http-only cookie after the user authenticates. When a request goes from the dashboard to the kubeapps-apis server, it goes through the oauth2 proxy which switches the cookie with the actual credential (the OIDC `id_token` for that user) which is then used for the interaction with the k8s API server. So it is actually the user interacting with the k8s API server - no impersonation involved.

Hope that makes sense. Let me know if you've got other questions or disagree with anything - happy to discuss further.

**Comment by ppbaena** [comment]
Thank you @absoludity for your detailed and accurate explanation. I am closing this proposal to directly talk with K8s API.

@dionysius feel free to re-open it if you consider that there is anything else related to this issue relevant to be included in Kubeapps.
