### ISSUE TITLE
Unable to edit or delete newly created flux package repository 

### ISSUE THREAD

**Issue by gfichtenholt** [vmware-tanzu/kubeapps#5542]
Scenario:
* user A has cluster admin access to namespace A
* user A logs in to portal, switch context to namespace A and creates a new flux repo there
* the repo is created successfully but EDIT, REFRESH and DELETE button are disabled. A bit ironic since REFRESH button was enabled in previous screen

Detailed repro steps:
See attached .txt file, some of steps 1-22, having to do with setting up ns A and user A 

screen 1
<img width="1440" alt="Screen Shot 2022-10-20 at 9 12 39 PM" src="https://user-images.githubusercontent.com/74032303/197110116-1f98b4e1-6285-494e-801c-2bdb657de58c.png">

screen 2
<img width="1440" alt="Screen Shot 2022-10-20 at 9 05 37 PM" src="https://user-images.githubusercontent.com/74032303/197109763-98354d95-b95a-41d1-85ab-433a7d591ce7.png">

[multi-tenant-setup.txt](https://github.com/vmware-tanzu/kubeapps/files/9835624/multi-tenant-setup.txt)

**Comment by antgamdia** [comment]
I guess this is an unintended side effect of #5480, @castelblanque ?

**Comment by gfichtenholt** [comment]
> I guess this is an unintended side effect of #5480, @castelblanque ?

I would be surprised. My bits are from several days ago.

**Comment by castelblanque** [comment]
It might be two issues together. On one side, in the example the context is namespace `a`  and the repo exists in namespace `a`, but it is being shown in the global part.
On the other side #5480 added a check for permissions, but precisely for Flux there is only the namespaced check done. No check for permissions in the global part, as there is no official global namespace for Flux.
Maybe we should change UI to show the repo in the namespaced section?

**Comment by gfichtenholt** [comment]
this division into global/namespaced doesn't really apply to flux very well. Its artificial. 
with flux you can use any repo that you have access to. does that mean global or namespaced? I don't know

**Comment by castelblanque** [comment]
Agree, but it is true that any repo is strictly namespaced, as it lives in a specific namespace. The "global" label is indeed artificial.
There could be a scenario where a user has a global Carvel repo and a Flux repo. In my opinion, in that case, UI should show the Carvel repo in the global section, and the Flux repo in the namespaced section (if context namespace is the one of the repo, of course).

**Comment by gfichtenholt** [comment]
yes, the repo "lives" in namespace X. But one may use the repo from namespace X to install a package in namespace Y, provided they have access to both X and Y. So is the repo global or namespaced? It sort of depends on "who's asking". If I am asking with the current context "X" maybe the answer is "namespaced". If I'm asking with the current context "Y" maybe the answer is "global"? Yikes

**Comment by castelblanque** [comment]
There is an upcoming redesign of the repositories UI that may ease this dichotomy, at least in that screen. #5515
I suggested to show all repos in a single table (not two different sections), and mark repos with a distinctive icon where considered "global" (i.e. packages can be installed into any ns).

**Comment by ppbaena** [comment]
+1 to this approach. It simplifies and improves the experience with a single list of repos and a field/column for the scope of each one. 

In addition, we should differentiate three scopes for package repositories:
- `Namespaced`
- `Cluster`
- `Multi-cluster`

IMO it is clearer than the current `global`, that it is valid for both `cluster` and `multi-cluster` scopes depending on the configuration. So we can have the following scenario:

| Cluster | Repository | Scope |
| ------- | ----------- | -------|
| Cluster A | Repo 1 | Namespaced |
| Cluster A | Repo 2 | Cluster |
| Cluster A | Repo 3 | Multi-cluster |
| Cluster B | Repo 3 | Multi-cluster |
| Cluster B | Repo 4 | Cluster |

Nowadays, `Repo 2`, `Repo 3` and `Repo 4` are all of them labeled as `global`.

**Comment by castelblanque** [comment]
Totally agree on the naming. `cluster`, `cluster-wide`,`cluster-level`..etc, sound more accurate instead of global.
Specially when it comes to multicluster, `global` gets confusing, e.g. "global to the cluster or global to multiple clusters?".
Is it ok if I create an issue to discuss the naming change?

**Comment by gfichtenholt** [comment]
So a flux repo would fall into which scope?

**Comment by gfichtenholt** [comment]
I have also verified that on the bits from main today that kubeapps-operator (cluster-admin to every namespace) will have the same problem (EDIT and DELETE buttons are disabled)

**Comment by gfichtenholt** [comment]
I just tried this scenario on bits I built locally just now and it is still broken

**Comment by dlaloue-vmware** [comment]
The new method is called “GetPackageRepositoryPermissions“. I do not see it listed in your screenshot.

On my machine, I still see the old “can-I’ calls.



From: Greg Fichtenholtz ***@***.***>
Date: Wednesday, November 16, 2022 at 10:19 PM
To: vmware-tanzu/kubeapps ***@***.***>
Cc: Dimitri Laloue ***@***.***>, State change ***@***.***>
Subject: Re: [vmware-tanzu/kubeapps] Unable to edit or delete newly created flux package repository (Issue #5542)
!! External Email

screenshots showing latest APIs are being used and UX still broken
[Screen Shot 2022-11-16 at 10 16 15 PM]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F74032303%2F202371115-c6e2df48-f294-4cd9-af6a-33fd2f03aaca.png&data=05%7C01%7Cdlaloue%40vmware.com%7C77261dfc16964a67e39008dac863a928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042627638973806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eh%2Fq%2FuV0LbfFxSF9%2FhZJIgkKZPAMTeScqJ4LNVnt73c%3D&reserved=0>
[Screen Shot 2022-11-16 at 10 16 32 PM]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F74032303%2F202371127-86f36df6-5fd3-417f-a09f-774172b2558d.png&data=05%7C01%7Cdlaloue%40vmware.com%7C77261dfc16964a67e39008dac863a928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042627638973806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3ae7nuPwbRkrC0bA%2BWXlbrQqDkLN8axWaHXcQEbTje0%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fkubeapps%2Fissues%2F5542%23issuecomment-1318141053&data=05%7C01%7Cdlaloue%40vmware.com%7C77261dfc16964a67e39008dac863a928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042627638973806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BKYM7MvBVlvgOjtg5a5AAYmaoGrzV1faO2Z2lqrK7gc%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARUYXATNWAY3DH5XKPTVCITWIXE6NANCNFSM6AAAAAARKY7SRQ&data=05%7C01%7Cdlaloue%40vmware.com%7C77261dfc16964a67e39008dac863a928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042627638973806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GNWLUDxq045xU9jq5kiHSK%2BMawKPfUYT%2By%2BHAmJ3mdw%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

!! External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by gfichtenholt** [comment]
> The new method is called “GetPackageRepositoryPermissions“. I do not see it listed in your screenshot. On my machine, I still see the old “can-I’ calls. 

I am guessing you didn't look carefully? 2nd screenshot, it is highlighted

**Comment by dlaloue-vmware** [comment]
ah, yes, missed it. …

I guess the issue is that the UI is considering the flux repos to be “global” (they are listed in the global, as I think the backend flags them as “namespaced: false”).
But then it looks in the “global” map built by the GetPermissions and sees everything as false because there is no cluster-wide rolebinding (as expected).

There was clearly no testing done 😊



From: Greg Fichtenholtz ***@***.***>
Date: Wednesday, November 16, 2022 at 10:29 PM
To: vmware-tanzu/kubeapps ***@***.***>
Cc: Dimitri Laloue ***@***.***>, State change ***@***.***>
Subject: Re: [vmware-tanzu/kubeapps] Unable to edit or delete newly created flux package repository (Issue #5542)
!! External Email

The new method is called “GetPackageRepositoryPermissions“. I do not see it listed in your screenshot. On my machine, I still see the old “can-I’ calls.

I am guessing you didn't look carefully? 2nd screenshot, it is highlighted

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fkubeapps%2Fissues%2F5542%23issuecomment-1318151156&data=05%7C01%7Cdlaloue%40vmware.com%7C705de1b7073945e7110908dac8651ac7%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042633821818417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WJ6iGNx4bZPn9kEcameR4GiTJoLHYQswl2Iu0uxyEt0%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARUYXASG5QSJLFJA3QBVB53WIXGFFANCNFSM6AAAAAARKY7SRQ&data=05%7C01%7Cdlaloue%40vmware.com%7C705de1b7073945e7110908dac8651ac7%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638042633821818417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8HYl8T4xVoMPzR0YDup2SOfXhI%2FcKhBWXVzdYHESnd0%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

!! External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by dlaloue-vmware** [comment]
There is still one issue, which was not fixed in this issue/pr as it applies to all plugins:  whenever the "show in all namespaces" witch is toggled on, then all actions for namespace repositories are disabled.

The reason is that the UI is fetching for permissions for global scope only, and not for all namespaces involved.
Such issue should be tackled as part of the repository UI revamp (issue #5515)
