### ISSUE TITLE
Actions (e.g. upgrade) disabled on installed OCI type helm charts from ACR

### ISSUE THREAD

**Issue by kstobbel** [vmware-tanzu/kubeapps#5833]
**Describe the bug**
At our company we recently moved all our Helm charts from a self-hosted Harbor instance to Microsoft's ACR. We use KubeApps in several projects to allow for customers to update certain K8S objects. One example of this is the management of a whitelist of IPs on top of a SFTP server running in K8S. We notice a difference in behaviour from KubeApps when having Harbor as a AppRepo compared to having ACR as a AppRepo: in the latter the UI shows the warning message that not all information for the installed package can be fetched and therefor some actions are disabled. When using Harbor, this issue does not exist. 

**To Reproduce**

1. Setup KubeApps and add an ACR instance (type = OCI) as AppRepo
2. Install a random Helm chart (Helm v3 supported) 
3. Try to upgrade the installed Helm chart --> "upgrade" button is disabled
4. Add a different AppRepo (type = Helm charts), in our case the old Harbor instance
5. Try to upgrade the installed Helm chart --> "upgrade" button is enabled and can be executed

**Expected behavior**
Installed Helm charts from ACR (type OCI) can be upgraded via the UI. 

**Deeper investigation**
I did some digging into this issue with the network tab from the browser and noticed that two operations are frequently called during the load of the "installed package" page in the UI: `GetInstalledPackageDetails` and `GetAvailablePackageDetails`. These two operations show different behaviour depending on the type of AppRepo installed:

1. AppRepo type = OCI (ACR)
The `GetInstalledPackageDetails` returns some details about the installed package, but in the request of the `GetAvailablePackageDetails` operation only the version of the package is provided (not the name or a reference to the chart) which makes me think that this operation won't be able to fetch details about the package on the AppRepo (the response of this call is also **empty**:

<img width="1218" alt="Screenshot 2023-01-06 at 13 27 55" src="https://user-images.githubusercontent.com/3177432/211013050-f7d0f24c-f3d6-492e-864f-6e73dd95cf27.png">

2. AppRepo type = Helm Charts (Harbor)
When using this AppRepo, the `GetInstalledPackageDetails` returns a bit more information, but more important, in the request of the `GetAvailablePackageDetails` operation the name of the package is provided together with the version (and in this case the response of this call is not empty):

<img width="1220" alt="Screenshot 2023-01-06 at 13 29 20" src="https://user-images.githubusercontent.com/3177432/211013277-39995486-52b4-4c5c-9aa0-5be426aec7d6.png">

**Desktop (please complete the following information):**

- Version 2.5.1
- Kubernetes version 1.24.6
- Package version Helm 3.8

**Additional context**
I came across this issue https://github.com/vmware-tanzu/kubeapps/issues/3253, and verified our Helm Chart but that does not seem to be related to our issue.

**Comment by absoludity** [comment]
Thank you for the excellent, detailed bug report @kstobbel . From the details you have provided, I suspect this is a difference not between Harbor and ACR, but rather, the default helm chart index format (a webserver with an index.yaml) and the OCI repository support (perhaps with some ACR specific difference, not sure).

Thanks to your details, the next step is to check in the frontend code *why* the name isn't being supplied to the call in that scenario (leaving it unable to upgrade). The OCI support is a bit limited in comparison, but should not be *that* limited :) 

[Looking at the code](https://github.com/vmware-tanzu/kubeapps/blob/fa761a001e54306f862e916e16f46968db84341b/dashboard/src/actions/installedpackages.ts#L117-L142), it appears that the call to `GetInstalledPackageDetail` succeeds, but is returning a result which has an incomplete `installedPackageDetail.availablePackageRef`.

[Following this through to the backend](https://github.com/vmware-tanzu/kubeapps/blob/fa761a001e54306f862e916e16f46968db84341b/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go#L620-L651), this only happens if, for some reason, the backend does not find a matching chart when it queries the database.

So we need to focus there and find out why, though the repo has been synced (successfully? The install was possible so assume so), the query does not return the available package. It may be related to the initial sync of the package. In fact, if you feel like digging, one obvious place to look would be to install both repos (your ACR OCI one and the normal harbor one), let them sync, then compare the postgresdb table record for that specific package and see if info is missing.

**Comment by kstobbel** [comment]
Hi @absoludity, thanks for the quick response. 
I did some further investigation based on your hint to check the database records for the packages and noticed two remarkable things:

- chart_name fields contain data with url encoded slashes for the OCI repo charts, e.g. <repo_name>/<folder_name>%2F<chart_name> (minor issue I guess, replacing %2F by '/' does not fix the issue)
-  in the `info` field in the charts records, the json path `chartVersions[*].urls` contains `null` values for the OCI repo charts and I would assume the `GetInstalledPackageDetail` returns this path, resulting in the issue (compared to the harbor one, this jsonpath do have a correct value pointing to a specific version of the chart file)

**Comment by absoludity** [comment]
Great, thanks for the extra information. We'll plan to triage and investigate further. I think the former point is not an issue (it means we can split on the `/` to get the repo and encoded chart name. But the latter may well indeed be related. Let's see.

**Comment by absoludity** [comment]
I was able to reproduce this and do some digging today and the issue is that when Kubeapps is displaying an installed package, the only information it has to look up the related available package, is the Helm release itself. But in the case of OCI helm charts, the release is just the information in the Chart.yaml (and the manifests)... it has no knowledge of the path prefixes that may have been in the available chart ID (and apparently, available chart name) in the case of an OCI repo.

So, as an example, I've created an OCI repository on the demo.harbor.io instance called `kubeapps` which has a chart `simple-chart` in it. Kubeapps syncs the data and creates a row in the DB with the info:

```
id  | repo      | namespace      | chart-id                        | info
199 | test-oci  | kubeapps       | test-oci/kubeapps%2Fsimplechart | {"ID": "test-oci/kubeapps%2Fsimplechart", "home": "", "icon": "", "name": "kubeapps%2Fsimplechart", ...
```

The chart id is correct and is what Kubeapps uses to lookup the available charts, but the Helm release object knows nothing of this, so when going from the Helm release of an installed package and looking for the related chart, we fail to find any (which is why the `AvailablePackageReference` is incomplete (it's actually empty) and an error is displayed in the UI.

So the solution will be (and I assume, was earlier - but will check), that the JSON `info`'s `name` field should have just the chart name as it is known to Helm (since we're looking this up using the Helm release info). So the above database entry should be:

```
id  | repo      | namespace      | chart-id                        | info
199 | test-oci  | kubeapps       | test-oci/kubeapps%2Fsimplechart | {"ID": "test-oci/kubeapps%2Fsimplechart", "home": "", "icon": "", "name": "simplechart", ...
```

where the `info->name` is just "simplechart" even though the kubeapps chart id continues to have the full data.

Unfortunately this regression has happened because it's only relevant to OCI repos (and Harbor unified Helm repos) which we don't yet test in our integration tests.
