### ISSUE TITLE
OIDC login with Keycloak and pinniped redirect to login page without showing any error message.

### ISSUE THREAD

**Issue by dinhhung2910** [vmware-tanzu/kubeapps#6105]
**Describe the bug**
I'm setting OIDC with kubeapps, pinniped, and keycloak. I can log in successfully, but it is immediately redirected to the login page without showing any error message.

**To Reproduce**
I have a self-managed k8s cluster. On this cluster, I have the following components:

* Keycloak, as an OIDC provider.
* pinniped-supervisor and pinniped-concierge.
* Proper RBAC for users in k8s cluster.

I can login kubectl successfully using pinniped.

Then I setup kubeapps using Bitnami helm chart, with auth-proxy enabled and pinniped-proxy enabled. I can login successfully, but then redirected immediately to the login page without any error.
I tried checking logs of container `auth-proxy` and container `pinniped-proxy`, but it couldn't find anything helpful:

*auth-proxy*
```
10.0.108.119:37407 - 0e4b74ec-5041-447e-a8ac-cb03ae2adc9a - hung.dinh@abc.com [2023/03/17 09:45:39] 174.129.210.72:32080 POST / "/apis/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 SECSSOBrowserChrome" 200 76 0.007
10.0.108.119:37407 - 6b5128b0-8456-4891-9628-1a101b9e1335 - hung.dinh@abc.com [2023/03/17 09:45:40] 174.129.210.72:32080 POST / "/apis/kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 SECSSOBrowserChrome" 200 0 0.015
```

*pinniped-proxy*
```
2023-03-17T09:45:40.319317 [ERROR] - Unauthorized by pinniped: authentication failed

Caused by:
    authentication failed
2023-03-17T09:45:40.319368 [INFO] - GET https://kubernetes.default/api/v1/namespaces/default 401 Unauthorized
2023-03-17T09:46:32.509823 [ERROR] - Unauthorized by pinniped: authentication failed

Caused by:
    authentication failed
2023-03-17T09:46:32.509871 [INFO] - GET https://kubernetes.default/api/v1/namespaces/default 401 Unauthorized
```

**Expected behavior**
It should be login to default cluster

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Version: 2.6.4
- Helm chart version: 12.2.7
- Kubernetes version: 1.26
- Package version 
    - Helm 3.11.2

**Additional context**
N/A

**Comment by absoludity** [comment]
Hi @dinhhung2910 . First, note that Kubeapps does not yet work with Pinniped Supervisor. See #5965  for more detail. Note that that issue describes a multi-cluster setup, but I think supervisor is still creating a separate jwt id_token for the target cluster even when there's only one.

So, if you are using supervisor, I assume what is happening is that:
- You are redirected to your Keycloak Identity provider and log in, which redirects you to Kubeapps
- Kubeapps (oauth2-proxy) uses the `id_token` provided supervisor to send a test request to the cluster (via pinniped)
- as your pinniped-proxy logs show, that `id_token` cannot be exchanged for a cert for the cluster (because pinniped-proxy does not know about supervisor, it's assuming the `id_token` was minted for that specific cluster.

You may be able to verify this by checking the pinniped (not pinniped-proxy) logs.

Currently your options are:

1. to not use supervisor, but rather just pinniped-concierge, as per the kubeapps docs, or
2. wait until we have supervisor support (not yet sure when we'll be able to do this)
3. Not use pinniped at all - this is an option if you can instead configure your cluster to trust your Keycloak identity provider (but I'm guessing you need to use pinniped, so this may not be an option).

Hope that helps. Let us know what you try.

**Comment by dinhhung2910** [comment]
Hi @absoludity , thanks for your very helpful comment.

I tried to skip pinniped-supervisor, and set up my JWTAuthenticator point directly to Keycloak endpoint as the issuer.
Now Kubeapps OIDC login works fine.

Thank you.

**Comment by absoludity** [comment]
Excellent, thanks for the update.
