### ISSUE TITLE
OIDC login with Keycloak and pinniped redirect to login page without showing any error message

### ISSUE THREAD

**Issue by dhanuJadhav123** [vmware-tanzu/kubeapps#6113]
I am trying to integrate kubeapps with Keycloak using pinniped-concierge. I can log in successfully, but it is immediately redirected to the login page without showing any error message.

**Comment by absoludity** [comment]
Hi @dhanuJadhav123 . Sorry, but I'll need more information to be able to help. You may be interested to read other people who have resolved the same issue using Keycloak and pinniped with Kubeapps. For example, most recently: #6105 .

If that does not help you resolve your issue, please provide more details, such as the relevant log lines in `pinniped-proxy` or pinniped concierge, which will show the reason *why* kubeapps thinks your credential does not have the required permissions.

I'll leave this open as I agree it would be great if Kubeapps actually showed more information, such as "Although you may have successfully authenticated with your identity provider, your credential is not recognized by the Kubernetes cluster."

**Comment by almadigabor** [comment]
I have the same issue with the github provider. Successful login, no error message, and after to callback it redirects to the login page.

**Comment by absoludity** [comment]
> I have the same issue with the github provider.

@almadigabor Do you mean that you're not using keycloak (the issue description here is about keycloak).

> Successful login, no error message, and after to callback it redirects to the login page.

That is a very normal response when your cluster does not trust the token minted by your identity provider (in this case, Github). 90% of requests we get about this are unrelated to Kubeapps itself but because people have not configured their cluster to trust their identity provider. If you have a chance, please work through our [OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/), and if after having worked through those you have verified that the cluster does trust your token (regardless of Kubeapps) then create an issue and we can look at your Kubeapps configuration. Hope that helps!
