### ISSUE TITLE
Upgrade Kubeapps internal demo environment

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#6126]
**Summary**
Upgrade the maintainers team demo environment in AKS

**Background and rationale**
Kubeapps maintainers team have a demo environment in AKS where some tests and demo are performed. This environment is out of date since Nov 22.

**Description**
Upgrade demo environment in AKS to Kubeapps 2.6.4

**Acceptance criteria**
Kubeapps 2.6.4 is up and running at the demo environment

**Comment by absoludity** [comment]
I haven't maintained a demo environment and have for years communicated that I would prefer that we be given time to make it easier for demo-ers, PMs etc., to practise spinning up their own environment to use for demos (which is what clients and the community have to do to demo in their internal environments.

That said, I can totally see the value in having something ready-to-use, and would be happy for us to setup and maintain a demo environment if that's what's decided. I'd push for non AKS (unless the oauth2-proxy azure bug has been fixed by MS and released) - as I don't think we should be running and maintaining a demo environment with hacks to work-around upstream issues when we don't have those issues on other platforms. I'd also be keen to ensure it was monitored so there are no surprises when people need to do a demo without warning (which is often the case, in my experience). Of course, this depends on resources available etc.
