### ISSUE TITLE
upgrade should be disabled when there is upgrade in progress 

### ISSUE THREAD

**Issue by vijimgowda** [vmware-tanzu/kubeapps#6147]
**Describe the bug**
when there is multiple version to upgrade for same tool , we will perform consecutive sequence upgrade , 
so when there is upgrade in progress ,  "upgrade" button  should be disabled. 

and also need to disable "upgrade" button when there application is upto date and in latest version 
 
**To Reproduce**

1. Go to 'kubeapps' select upgrade available version 
2. Click on 'upgrade and 'click on deploy' and select one more version and click on upgrade deploy the version  
3. should not allow to deploy one more version while deploying in progress 

**Expected behavior**
upgrade button should be disabled while there is deployment in progress 
and also upgrade button should be disabled when application is in latest version 

- Kubernetes version- 1.22
- Package version - Helm 3.2,

**Comment by absoludity** [comment]
Hi @vijimgowda , thanks for creating the issue and providing input!

> when there is multiple version to upgrade for same tool , we will perform consecutive sequence upgrade , so when there is upgrade in progress , "upgrade" button should be disabled.

Hmm, remember that for Kubernetes and Helm, upgrading something is just applying some YAML configuration, your desired state, which the system then begins actualising (turning your desired state into the actual state), so hitting upgrade there is just updating the desired state, which you can do even if the current desired state isn't the actual state.

Or a simpler way of thinking about this: Does `kubectl` or the `helm` CLI, allow you to upgrade while an upgrade is in progress? (Remember, Kubeapps is a pretty UI around Helm and other packaging tools - we try to stick to the same behavior).

> 
> and also need to disable "upgrade" button when there application is upto date and in latest version

Again, worth considering whether this is the case for the `helm` CLI, and if not, why not? It isn't the case (that is, the `helm` CLI allows you to "upgrade" a deployment even if you're already on the latest version) because again, upgrading is just specifying a new desired state (by applying YAML), so even though you may not be changing to a newer version, if you need to change the configuration of the current version, it's still an "upgrade". This is confusing I agree, and I wonder if it's an area we can improve on without changing the functionality provided by the `helm` CLI. For example, we could change the button to display "Apply changes" if not changing the version, or "Downgrade" if an earlier version is selected. But either way, I don't think we can disable the button?

Let me know if you disagree :)
