### ISSUE TITLE
Sync OCI repositories no longer work

### ISSUE THREAD

**Issue by overag3** [vmware-tanzu/kubeapps#6484]
**Describe the bug**
With the latest version of chart (12.4.7), OCI repositories are no longer synchronized.

**To Reproduce**

1. Deploy new version of chart
2. Login
3. See error

**Screenshots**

![error-oci-repo-01](https://github.com/vmware-tanzu/kubeapps/assets/54666189/0810f353-c5eb-4138-8ae5-096596e34ef8)
![error-oci-repo-02](https://github.com/vmware-tanzu/kubeapps/assets/54666189/9e46e390-36bf-4558-996e-1dc49387ff86)

**Desktop (please complete the following information):**

- Chart Kubeapps version 12.4.7
- Rancher Kubernetes v1.24.7+rke2r1

**Additional context**

Logs of asset-syncer
```
I0718 09:06:16.559251       1 root.go:32] asset-syncer has been configured with: server.Config{DatabaseURL:"kubeapps-postgresql:5432", DatabaseName:"assets", DatabaseUser:"postgres", DatabasePassword:"REDACTED", Debug:false, Namespace:"kubeapps", OciRepositories:[]string{"xxx/postgresql", "yyy/mariadb"}, TlsInsecureSkipVerify:false, FilterRules:"", PassCredentials:false, UserAgent:"asset-syncer/2.8.0 (kubeapps/2.8.0)", UserAgentComment:"kubeapps/2.8.0", GlobalPackagingNamespace:"kubeapps", KubeappsNamespace:"", AuthorizationHeader:"Basic <token>", DockerConfigJson:""}
I0718 09:06:16.609965       1 sync.go:77] Last checksum: 
panic: runtime error: index out of range [0] with length 0

goroutine 61 [running]:
github.com/vmware-tanzu/kubeapps/cmd/asset-syncer/server.(*OCIRegistry).Charts.func3()
    /bitnami/blacksmith-sandox/kubeapps-asset-syncer-2.8.0/src/github.com/vmware-tanzu/kubeapps/cmd/asset-syncer/server/utils.go:682 +0x1e9
created by github.com/vmware-tanzu/kubeapps/cmd/asset-syncer/server.(*OCIRegistry).Charts
    /bitnami/blacksmith-sandox/kubeapps-asset-syncer-2.8.0/src/github.com/vmware-tanzu/kubeapps/cmd/asset-syncer/server/utils.go:679 +0x3b2
Stream closed EOF for kubeapps/apprepo-xxx-kubeapps-sync-xxxl-28161186-gwtkd (sync)
```

Logs of PostgreSQL DB
```
2023-07-18 09:10:01.196 GMT [1378] ERROR:  relation "repos" does not exist at character 22
2023-07-18 09:10:01.196 GMT [1378] STATEMENT:  SELECT checksum FROM repos WHERE name = $1 AND namespace = $2
2023-07-18 09:10:02.062 GMT [1393] ERROR:  relation "repos" does not exist at character 22
2023-07-18 09:10:02.062 GMT [1393] STATEMENT:  SELECT checksum FROM repos WHERE name = $1 AND namespace = $2
2023-07-18 09:10:16.592 GMT [1409] ERROR:  relation "repos" does not exist at character 22
2023-07-18 09:10:16.592 GMT [1409] STATEMENT:  SELECT checksum FROM repos WHERE name = $1 AND namespace = $2
2023-07-18 09:10:44.577 GMT [1453] ERROR:  relation "repos" does not exist at character 22
2023-07-18 09:10:44.577 GMT [1453] STATEMENT:  SELECT checksum FROM repos WHERE name = $1 AND namespace = $2
```

We do not encounter this problem with bitnami charts repository. Our private repository is Harbor (OCI repositories) in version v2.6.2-498e7e21.
The synchronization was works before updating to the latest version of chart.

Regards

**Comment by absoludity** [comment]
Can you paste a redacted version of your `AppRepository` CR please? I'm trying to see what may have caused a change here, but knowing that OCI repos are working in CI and other tests, I'm keen to see if something is different with yours.

**Comment by overag3** [comment]
Here is our `AppRepository` CR for our repository xxx
```
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeapps.com/v1alpha1","kind":"AppRepository","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argocd-xxx_kubeapps","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kubeapps","helm.sh/chart":"kubeapps-12.4.7"},"name":"xxx","namespace":"xxx-kubeapps"},"spec":{"auth":{"header":{"secretKeyRef":{"key":"authorizationHeader","name":"apprepo-xxx-secrets"}}},"ociRepositories":["project1-prod/postgresql","project1-prod/mariadb"],"syncJobPodTemplate":{"spec":{"securityContext":{"runAsUser":1001}}},"type":"oci","url":"https://harbor.<mydomain>.com/"}}
  creationTimestamp: "2023-07-18T08:30:05Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: argocd-xxx_kubeapps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeapps
    helm.sh/chart: kubeapps-12.4.7
  name: xxx
  namespace: xxx-kubeapps
  resourceVersion: "170148453"
  uid: d507f9ff-a3c2-48f1-ac72-ddc2fce69f0f
spec:
  auth:
    header:
      secretKeyRef:
        key: authorizationHeader
        name: apprepo-xxx-secrets
  ociRepositories:
  - project1-prod/postgresql
  - project1-prod/mariadb
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 1001
  type: oci
  url: https://harbor.<mydomain>.com/
```

**Comment by absoludity** [comment]
Thanks @overag3. So I've tried to reproduce this today... what I did:

1. Created a project on harbor and uploaded an OCI chart there.
2. Added the app repo via the Kubeapps UX
3. Verified that the catalog in the UX was updated
4. Deleted the postgres DB (to ensure that the schema would be missing, since this is part of what I see in the logs of yours, so just in case it's related)
5. Waited for the next sync job to run... which ran without issue (the db schema was re-created).

My app repo looks like:

```yaml
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  creationTimestamp: "2023-07-20T01:55:42Z"
  generation: 1
  name: bitnami-oci
  namespace: kubeapps
  resourceVersion: "77988"
  uid: 78d5ea19-23f3-447c-9d54-1cad7cb6bd5e
spec:
  auth:
    header:
      secretKeyRef:
        key: authorizationHeader
        name: apprepo-bitnami-oci
  filterRule:
    jq: ""
  interval: 10m
  ociRepositories:
  - nginx
  resyncRequests: 0
  syncJobPodTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
      securityContext: {}
  type: oci
  url: https://demo.goharbor.io/kubeapps
status:
  status: ""
```

Then I noticed that a difference between your and my app repositories is that you've entered your registry URI without the project suffix (project1-prod) and instead included that on the listed repositories. So I deleted my app repo and added a new one with that setup instead, so I end up with the following yaml stored (after adding it via the UX):

```yaml
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  creationTimestamp: "2023-07-20T02:32:01Z"
  generation: 1
  name: harbor-test-2
  namespace: kubeapps
  resourceVersion: "81153"
  uid: e91ff7c7-c03e-4c08-a397-7a1408679f0e
spec:
  auth:
    header:
      secretKeyRef:
        key: authorizationHeader
        name: apprepo-harbor-test-2
  filterRule:
    jq: ""
  interval: 10m
  ociRepositories:
  - kubeapps/nginx
  resyncRequests: 0
  syncJobPodTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
      securityContext: {}
  type: oci
  url: https://demo.goharbor.io/
status:
  status: ""
```
which matches your example more closely. That also worked without issue, so I again deleted the postgres db and waited for the next sync job to run which does indeed result in an error, but a different error to yours :/

```
Error: Error: GET request to [https://demo.goharbor.io/v2/charts-index/manifests/latest] failed due to status [400]: {"errors":[{"code":"BAD_REQUEST","message":"bad request: invalid repository name: charts-index"}]}
```
which I'll look into separately.

So, the data that I have currently is:
1. Your database schema was empty when you added the repo - this should not be a problem in and of itself as it's a cache that is re-created when the sync runs (but your sync is not running). Note that your screenshots are simply for this reason and not indicating the actual problem.
2. Your sync is failing in a way that I can't yet reproduce. In particular, it's panicing (and un-handled error) at a point in the code which would indicate that the data Kubeapps receives about one of your two repositories has no tags (this seems to be the `index out of range [0] with length 0`.

I don't suppose there's any chance your repos there don't have tags pushed yet? (We should better handle that case anyway).

I'll look at the error I saw and see if it's a simple fix too.

Thanks.

**Comment by overag3** [comment]
I closed this issue, the problem came from that we wanted to synchronize a Harbor project which was empty (without artifacts).

Sorry for the wasted time. 😅 
Regards
