### ISSUE TITLE
login via keycloak fail:redirect got nothing

### ISSUE THREAD

**Issue by cwyj** [vmware-tanzu/kubeapps#6734]
i deploy a kubeapps by helm chart 4.0.4，and want to login with oidc provider by keycloak.
here is my keycloak client Valid redirect URIs config and charts values.yaml authProxy config,please help me figure out where the wrong is.

<img width="1261" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/69233482-cf03-4469-9957-0ad9174cfa39">

`authProxy:
  enabled: true
  
  external: false
  
  oauthLoginURI: http://9.199.116.70:8080/oauth2/callback
  oauthLogoutURI: http://9.199.116.70:8080/oauth2/callback
  
  image:
    registry: mirrors.tencent.com
    repository: kubeapps/oauth2-proxy
    tag: 6.1.1-debian-10-r12
    pullPolicy: IfNotPresent

  ## Mandatory parameters for the internal auth-proxy.
  ##
  provider: "oidc"
  clientID: "kubeapps"
  clientSecret: "0ojed2TmFzj0w2JaizfKhXJKoFPvTizf"
  cookieSecret: "bm90LWdvb2Qtc2VjcmV0Cg=="
  ## Use "example.com" to restrict logins to emails from example.com
  emailDomain: "*"
  ## Additional flags for oauth2-proxy
  ##
  additionalFlags:
    - --ssl-insecure-skip-verify=true
    - --cookie-secure=false
    - --scope=openid email groups
    - --oidc-issuer-url=https://11.39.228.48:8443/realms/kubeapps
    - --redirect-url=http://9.199.116.70:8080`

https://11.39.228.48:8443 is my keycloak server,its works well.
http://9.199.116.70:8080 is my kubeapps,its works well if not use authProxy.

after click "login via oidc provider",web redirect to  http://9.199.116.70:8080/oauth2/callback/,oauthLoginURI set it,but i got nothing.
<img width="1720" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/32be7cb1-dad9-4448-97d3-365411519039">

**Comment by absoludity** [comment]
Hi @cwyj . I assume you've already seen and used our  [Kubeapps OIDC with keycloak](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/) docs?

Looking at your setup:

> oauthLoginURI: http://9.199.116.70:8080/oauth2/callback
> oauthLogoutURI: http://9.199.116.70:8080/oauth2/callback

I think these values are incorrect - these are not for the callback URL to which your identity provider (key-cloak) should redirect, but rather, are the URLs which Kubeapps' UI should redirect to for login and logout, which is (also) handled by the oauth2-proxy service. I'd revert these to use the default values which are handled by the oauth2-proxy service for initiating login and logout (see their comments in the values.yaml to confirm).

I assume what's happening right now is that your keycloak instance is redirecting, after successful auth, to the /oauth2/callback endpoint, as it should, because you've set this in your KeyCloak configuration ("Valid Redirect URIs"), which is then handled by oauth2-proxy but then once Kubeapps gets the token and tests it, it is probably failing so that Kubeapps then redirects to the login URL, which you've currently set as /oauth2/callback - so it redirects there and you get the page you see. Hope that makes sense.

Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify *why* the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).

Hope that helps!

**Comment by cwyj** [comment]
> Hi @cwyj . I assume you've already seen and used our [Kubeapps OIDC with keycloak](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/) docs?
> 
> Looking at your setup:
> 
> > oauthLoginURI: http://9.199.116.70:8080/oauth2/callback
> > oauthLogoutURI: http://9.199.116.70:8080/oauth2/callback
> 
> I think these values are incorrect - these are not for the callback URL to which your identity provider (key-cloak) should redirect, but rather, are the URLs which Kubeapps' UI should redirect to for login and logout, which is (also) handled by the oauth2-proxy service. I'd revert these to use the default values which are handled by the oauth2-proxy service for initiating login and logout (see their comments in the values.yaml to confirm).
> 
> I assume what's happening right now is that your keycloak instance is redirecting, after successful auth, to the /oauth2/callback endpoint, as it should, because you've set this in your KeyCloak configuration ("Valid Redirect URIs"), which is then handled by oauth2-proxy but then once Kubeapps gets the token and tests it, it is probably failing so that Kubeapps then redirects to the login URL, which you've currently set as /oauth2/callback - so it redirects there and you get the page you see. Hope that makes sense.
> 
> Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify _why_ the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).
> 
> Hope that helps!

@absoludity hello，thanks for your answer.
i have already seen and Follow your documentation exactly （https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/）,but my redirct still not working.
Here is my redirect config:
Keycloak Valid redirect URIs is http://9.199.116.70:8080/oauth2/callback（9.199.116.70:8080 is my kubeapps web url）
oauthLoginURI and oauthLogoutURI in kubeapps values.yaml use the default values:
oauthLoginURI: /oauth2/start
oauthLogoutURI: /oauth2/sign_out

After click "login via oidc provider",web redirect to http://9.199.116.70:8080/oauth2/start/,and then the condition is the same as before.the logs of oauth2-proxy not give any info.

Any other suggestions for me?thanks.

**Comment by cwyj** [comment]
<img width="1715" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/70fe69b9-5bad-454b-ae2e-62da78c6c603">
i got 403 Forbidden when request http://9.199.116.70:8080/api/clusters/tke01/，tke01 is one of the k8s clusters added in kubeapps.

**Comment by cwyj** [comment]
> <img alt="image" width="1715" src="https://user-images.githubusercontent.com/22216714/269186840-70fe69b9-5bad-454b-ae2e-62da78c6c603.png"> i got 403 Forbidden when request http://9.199.116.70:8080/api/clusters/tke01/，tke01 is one of the k8s clusters added in kubeapps.

here is my cluster config in values.yaml,certificateAuthorityData and token should be correct，but got 403.
<img width="1448" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/2023d393-c8fb-4d1e-a73d-472ed23f9394">

**Comment by absoludity** [comment]
> > Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify _why_ the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).
> > Hope that helps!
> 
> @absoludity hello，thanks for your answer. i have already seen and Follow your documentation exactly （[https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/）,but](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/%EF%BC%89,but) my redirct still not working. Here is my redirect config: Keycloak Valid redirect URIs is [http://9.199.116.70:8080/oauth2/callback（9.199.116.70:8080](http://9.199.116.70:8080/oauth2/callback%EF%BC%889.199.116.70:8080) is my kubeapps web url） oauthLoginURI and oauthLogoutURI in kubeapps values.yaml use the default values: oauthLoginURI: /oauth2/start oauthLogoutURI: /oauth2/sign_out
> 
> After click "login via oidc provider",web redirect to http://9.199.116.70:8080/oauth2/start/,and then the condition is the same as before.the logs of oauth2-proxy not give any info.
> 
> Any other suggestions for me?thanks.

Yes, as above :) :

> > Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify _why_ the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).
> > Hope that helps!

> <img alt="image" width="1715" src="https://user-images.githubusercontent.com/22216714/269186840-70fe69b9-5bad-454b-ae2e-62da78c6c603.png"> i got 403 Forbidden when request http://9.199.116.70:8080/api/clusters/tke01/，tke01 is one of the k8s clusters added in kubeapps.

Yes, you'll need to follow the debugging instructions (which will give you a way to test your authentication *without* using Kubeapps) and figure out *why* your cluster is rejecting the auth. I'm sorry, but I can't manually debug the oidc setup of your clusters - you'll need to do the work for that. That said, I am happy to help once you have done that and have found the underlying issue (unrelated to Kubeapps).

**Comment by cwyj** [comment]
> > > Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify _why_ the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).
> > > Hope that helps!
> > 
> > 
> > @absoludity hello，thanks for your answer. i have already seen and Follow your documentation exactly （[https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/）,but](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/%EF%BC%89,but) my redirct still not working. Here is my redirect config: Keycloak Valid redirect URIs is [http://9.199.116.70:8080/oauth2/callback（9.199.116.70:8080](http://9.199.116.70:8080/oauth2/callback%EF%BC%889.199.116.70:8080) is my kubeapps web url） oauthLoginURI and oauthLogoutURI in kubeapps values.yaml use the default values: oauthLoginURI: /oauth2/start oauthLogoutURI: /oauth2/sign_out
> > After click "login via oidc provider",web redirect to http://9.199.116.70:8080/oauth2/start/,and then the condition is the same as before.the logs of oauth2-proxy not give any info.
> > Any other suggestions for me?thanks.
> 
> Yes, as above :) :
> 
> > > Once you do get your redirect working, I'm guessing that you will find that the authentication is failing and leaving you back on the Kubeapps login page. Be sure to then work through the [Kubeapps OIDC debugging steps](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/) if you have any further issues, as this will help you identify _why_ the token returned by your identity provider (keycloak) is not able to be used (in particular, you can test the token against your k8s server without using Kubeapps at all).
> > > Hope that helps!
> 
> > <img alt="image" width="1715" src="https://user-images.githubusercontent.com/22216714/269186840-70fe69b9-5bad-454b-ae2e-62da78c6c603.png"> i got 403 Forbidden when request [http://9.199.116.70:8080/api/clusters/tke01/，tke01](http://9.199.116.70:8080/api/clusters/tke01/%EF%BC%8Ctke01) is one of the k8s clusters added in kubeapps.
> 
> Yes, you'll need to follow the debugging instructions (which will give you a way to test your authentication _without_ using Kubeapps) and figure out _why_ your cluster is rejecting the auth. I'm sorry, but I can't manually debug the oidc setup of your clusters - you'll need to do the work for that. That said, I am happy to help once you have done that and have found the underlying issue (unrelated to Kubeapps).

i follow the debugging instructions,add --set-authorization-header=true  args to oauth2-proxy.but there is no Authorization header in the Response headers.
<img width="1702" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/8632f0e0-af9b-4589-ac4a-2cf8333b2506">
Version：oauth2-proxy:7.1.2-debian-10-r22
Args:
        - --provider=oidc
        - --client-id=kubeapps
        - --client-secret=ZoCV6nCBSPCEtjcWJibcj5zcv3N6u3Fy
        - --cookie-secret=bm90LWdvb2Qtc2VjcmV0Cg==
        - --upstream=http://localhost:8080/
        - --http-address=0.0.0.0:3000
        - --email-domain=*
        - --pass-basic-auth=false
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --skip-auth-regex=^\/config\.json$
        - --skip-auth-regex=^\/favicon.*\.png$
        - --skip-auth-regex=^\/static\/
        - --skip-auth-regex=^\/$
        - --scope=openid email groups
        - --ssl-insecure-skip-verify
        - --cookie-secure=false
        - --scope=openid email groups
        - --oidc-issuer-url=https://11.39.228.48:8443/realms/kubeapps
        - --set-authorization-header=true

**Comment by cwyj** [comment]
By the way,my goal is use kubeapps manage multi clusters.Must oidc certification be supported first？

**Comment by absoludity** [comment]
> By the way,my goal is use kubeapps manage multi clusters.Must oidc certification be supported first？

Yes, if you want to manage apps (remember, Kubeapps is about managing apps, not clusters) across multiple clusters and want people to login once, then yes, your clusters need to support OIDC and a single identity provider (unrelated to Kubeapps).

> i follow the debugging instructions,add --set-authorization-header=true args to oauth2-proxy.but there is no Authorization header in the Response headers.

That would happen if you were never redirected to your identity provider (Keycloak) to authenticate? You said above

> After click "login via oidc provider",web redirect to http://9.199.116.70:8080/oauth2/start/,and then the condition is the same as before.the logs of oauth2-proxy not give any info.

Do you get redirected from /oauth2/start/ to your key cloak instance, where you authenticate, before being redirected back to /oauth2/callback ? If so, then you should find more relevant information in your oauth2-proxy logs.

Another question: are you using the oauth2-proxy that's comes pre-configured in Kubeapps (ie. with `authProxy.enabled: true`)? The reason I ask is because it's not clear to me from above, in fact, you mention your oauth2-proxy setup as if it is separate. If it was separate then your redirect URLs would be incorrect, since the keycloak is redirecting to oauth2-proxy, not Kubeapps.

Kubeapps itself is unrelated to the authentication - it simply redirects to let oauth2-proxy handle authentication and then after (successful) authentication on your identity provider (key cloak),  oauth2-proxy sets an http-only cookie for Kubeapps, which is used transparently for requests. Kubeapps knows nothing other than whether the requests it makes are successful. Please check your oauth2-proxy setup, logs, etc.

**Comment by cwyj** [comment]
> Yes, if you want to manage apps (remember, Kubeapps is about managing apps, not clusters) across multiple clusters and want people to login once, then yes, your clusters need to support OIDC and a single identity provider (unrelated to 
Kubeapps).

yeah,I misstated it.I want to managing apps across multiple clusters.And I am sure that my clusters already support OIDC by Keycloak,because i can get correct id_token  to access my cluster api.

> That would happen if you were never redirected to your identity provider (Keycloak) to authenticate?

Yes,its seem to not redirected to my Keycloak to authenticate.
When i type http://9.199.116.70:8080/（my kubeapps web addr） in the browser,link jumps to http://9.199.116.70:8080/#/login,this moment i got 403 error for my cluster01.
<img width="1720" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/8e8bcf37-d783-4942-aa11-317b099b12cb">
And then i click "login via oidc provider" on web,link jumps to http://9.199.116.70:8080/oauth2/start/.(/oauth2/start/ is oauthLoginURI which default value set in values.yaml).Finally  browser leave me a Blank page.
So i think i was never redirected to my identity provider.

> Another question: are you using the oauth2-proxy that's comes pre-configured in Kubeapps (ie. with authProxy.enabled: true)? The reason I ask is because it's not clear to me from above, in fact, you mention your oauth2-proxy setup as if it is separate. If it was separate then your redirect URLs would be incorrect, since the keycloak is redirecting to oauth2-proxy, not Kubeapps.

Yes i set authProxy.enabled: true.I posted all the configurations about the authProxy（delete comment otherwise too long）：
`authProxy:
  enabled: true
  external: false
  oauthLoginURI: /oauth2/start
  oauthLogoutURI: /oauth2/sign_out
  image:
    registry: mirrors.tencent.com
    repository: kubeapps/oauth2-proxy
    tag: 7.1.2-debian-10-r22
    pullPolicy: IfNotPresent
  provider: "oidc"
  clientID: "kubeapps"
  clientSecret: "ZoCV6nCBSPCEtjcWJibcj5zcv3N6u3Fy"
  cookieSecret: "bm90LWdvb2Qtc2VjcmV0Cg=="
  emailDomain: "*"
  additionalFlags:
    - --ssl-insecure-skip-verify
    - --cookie-secure=false
    - --scope=openid email groups
    - --oidc-issuer-url=https://11.39.228.48:8443/realms/kubeapps
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 32Mi`

@absoludity Thank you very much for helping me, It's been bothering me for a long time.

**Comment by absoludity** [comment]
> And then i click "login via oidc provider" on web,link jumps to http://9.199.116.70:8080/oauth2/start/.(/oauth2/start/ is oauthLoginURI which default value set in values.yaml).Finally browser leave me a Blank page.
> So i think i was never redirected to my identity provider.

OK, let's work from here, as I'm about 85% sure this is the issue. First, just be be sure, can you *unset* those values in your values.yaml, so that it just uses the default values (`/oauth2/start` - note that there's no trailing slash in the default value).

Please note that this value is set *because* it's the default path with which oauth2-proxy will itself handle logins - see [oauth2-proxy endpoints](https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints) . Kubeapps is not involved in this at all (if the auth proxy is enabled, it is handling the requests before even the Kubeapps frontend). So the next piece of evidence that we need is the logs of the authproxy service. You can find these with `kubectl -n kubeapps logs your-kubeapps-frontend-pod -c auth-proxy`

**Comment by cwyj** [comment]
I have sent email to you,it may be more efficient.Please forgive me if I disturb you.Look forward to hearing from you. @absoludity

**Comment by cwyj** [comment]
> > And then i click "login via oidc provider" on web,link jumps to http://9.199.116.70:8080/oauth2/start/.(/oauth2/start/ is oauthLoginURI which default value set in values.yaml).Finally browser leave me a Blank page.
> > So i think i was never redirected to my identity provider.
> 
> OK, let's work from here, as I'm about 85% sure this is the issue. First, just be be sure, can you _unset_ those values in your values.yaml, so that it just uses the default values (`/oauth2/start` - note that there's no trailing slash in the default value).
> 
> Please note that this value is set _because_ it's the default path with which oauth2-proxy will itself handle logins - see [oauth2-proxy endpoints](https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints) . Kubeapps is not involved in this at all (if the auth proxy is enabled, it is handling the requests before even the Kubeapps frontend). So the next piece of evidence that we need is the logs of the authproxy service. You can find these with `kubectl -n kubeapps logs your-kubeapps-frontend-pod -c auth-proxy`

hey,I haven't received your email reply yet.
you said unset those values,i do not know what is it means? Now it just uses the default values for authProxy part in values.yaml.Compare with https://github.com/vmware-tanzu/kubeapps/blob/v2.0.0/chart/kubeapps/values.yaml.
<img width="1272" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/95625c37-17d6-4005-b164-ece1a64cf034">
This is the log of auth-proxy.It doesn't seem to have any useful information.

**Comment by absoludity** [comment]
> I have sent email to you,it may be more efficient.Please forgive me if I disturb you.Look forward to hearing from you. @absoludity

Thanks @cwyj . For a bunch of reasons, it's important to keep the discussion here :)

> you said unset those values,i do not know what is it means? Now it just uses the default values for authProxy part in values.yaml.Compare with https://github.com/vmware-tanzu/kubeapps/blob/v2.0.0/chart/kubeapps/values.yaml.

Some of your pastes had "/oauth2/start/" (note the extra trailing slash) as the oauthLoginURL, rather than the default "/oauth2/start" (note no trailing slash). I just wanted to make sure you were using the correct default value, as this is what oauth2-proxy will be serving.

> Auth-proxy logs and kubeapps nginx log I send you.

Thanks, so you sent both the nginx and auth-proxy logs - perfect, so from those, we can see that although the nginx log shows the request to /oauth2/start as expected:

2023-09-21T04:13:03.947027246Z 11.176.16.155 - - [21/Sep/2023:04:13:03 +0000] "GET /oauth2/start HT
TP/1.1" 301 162 "http://9.199.116.70:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

the oauth-proxy logs do not have a corresponding entry, with no entries after it starts listening:

```
2023-09-21T04:12:26.133046852Z [2023/09/21 04:12:26] [logger.go:490] OAuthProxy configured for OpenID Connect Client ID: kubeapps
2023-09-21T04:12:26.133048996Z [2023/09/21 04:12:26] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
2023-09-21T04:12:26.133155494Z [2023/09/21 04:12:26] [logger.go:490] HTTP: listening on 0.0.0.0:3000
```

Haha - OK, and that just made me realise why. So when you enable oauth for Kubeapps, all the chart does is (1) ensure that the auth-proxy container runs on the frontend (which is working fine for you), and (2) updates the p[ort that is exposed by the kubeapps frontend service](https://github.com/vmware-tanzu/kubeapps/blob/2cb6c8a7f1e824a8ba851d48a316417cf6d49c8f/chart/kubeapps/templates/frontend/service.yaml#L41-L45) so that rather than the service targeting the http port, it instead targets the port of the oauth-proxy service (3000).

That happens so that you don't have to know about it, because normally you'd be accessing Kubeapps through the k8s exposed service. But the whole time in your notes above, you're explicitly using :8080 , bypassing the service. I think if you instead use port 3000 (as the service does for you, if you used it), you'll find your request to `/oauth2/start` is then handled by the oauth-proxy service (and will see the entry in the log).

Try that, it should help you move forward (though there may be other issues). Good luck :)

**Comment by cwyj** [comment]
> But the whole time in your notes above, you're explicitly using :8080 (which is the port exposed by the nginx http prontend) , bypassing the service. I think if you instead use port 3000

Yes,I should use auth proxy port 3000 instead of nginx port 8080....In our environment,k8s pod can directly expose its service by pod ip to our LAN, instead of via ingress or service. Maybe there should be a hint in kubeapps values.yaml about auth proxy is front of nginx,using port 3000 after enable auth proxy.

Now my kubeapps supported multi clusters is working well.Thanks for your help! @absoludity

**Comment by absoludity** [comment]
Excellent, glad we could find the issue :)
