### ISSUE TITLE
[HELP] KubeApps API and OIDC auth

### ISSUE THREAD

**Issue by drew-viles** [vmware-tanzu/kubeapps#6792]
**Summary**
I need to get the KubeApps API working with OIDC authentication.

**Background and rationale**
ok, I'll try and set the scene here and be as clear (verbose) as possible but apologies in advanced if it sounds like nonsense 😆 

I have a managed service I'm building which has a user interface for deploying k8s clusters and I want to offer a few apps up via KubeApps to the users of said managed service which also includes some apps from a repo I've added that uses Harbor. The clusters are not deployed with OIDC so have pinniped deployed along with auth proxy - this could change if it's needed. The UI works fine with this approach so I know it's working there as expected.

I've built a Golang app that acts as a proxy between my UI and KubeApps and it queries the [KubeApps API](https://app.swaggerhub.com/apis/kubeapps/Kubeapps/0.1.0#/) to pull available packages, offer up the values to the customers and allows them to deploy and manage apps - essentially recreating the KubeApps interface in a minimal way and inside my own UI.

Now, I can get this working fine when using the Bearer Token [as described here](https://kubeapps.dev/docs/latest/reference/developer/kubeapps-apis/#testing-an-authenticated-endpoint). What I'm having trouble with is getting it working via the OIDC method. I've tried following [this approach](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/#viewing-the-jwt-id-token) but I'm failing to get anywhere with it. When running the `curl -H "Authorization: Bearer $TOKEN" https://my.k8s.cluster/` command it suggests, it fails and if I try using the same approach as a dirty test to see if auth works from the Go app, it fails in the same way. The failure is that it is returning the login page and asking me to authenticate with the OIDC provider. 

**Description**
I understand that the OIDC auth for all clusters needs to be configured to use the same provider which in our case is Dex and as the UI is working, I can only presume it's configured correctly. I'm able to login, list packages, deploy them and everything else you can do via the supplied UI. 

I feel like I'm either missing a something around OIDC here

OR

Missing a chunk of documentation somewhere that will explain to me the steps I need to get OIDC auth working with the API. 

OR 

Based on the [guide here](https://kubeapps.dev/docs/latest/reference/developer/kubeapps-apis/#an-aggregated-api-server---combining-results-from-different-packaging-plugins) whether I should be using the KubeApps API as a go module instead of hitting the REST endpoint.

OR

If I'm just not able to do what I'm trying to achieve and the the multi-cluster approach is designed in such a way that it works for the KubeApps UI and the API cannot be used as I wish to use it.

**Additional context**
I could just hit the Harbor API directly and I've got a working demo of this going already but before I started essentially replicating the  API provided by KubeApps with regards to managing the apps, thought I'd open this to see if you can help me see the wood for the trees.

Of course you can just tell me, after reading all of this, to go away 😆 

Thanks!

**Comment by absoludity** [comment]
> I've built a Golang app that acts as a proxy between my UI and KubeApps and it queries the [KubeApps API](https://app.swaggerhub.com/apis/kubeapps/Kubeapps/0.1.0#/) to pull available packages, offer up the values to the customers and allows them to deploy and manage apps - essentially recreating the KubeApps interface in a minimal way and inside my own UI.

Nice! That's exactly why we separated the functionality of the KubeappsAPIs service, to enable situations like that.

> Now, I can get this working fine when using the Bearer Token [as described here](https://kubeapps.dev/docs/latest/reference/developer/kubeapps-apis/#testing-an-authenticated-endpoint). What I'm having trouble with is getting it working via the OIDC method. I've tried following [this approach](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/#viewing-the-jwt-id-token) but I'm failing to get anywhere with it. 

It's not clear to me whether you mean that you can't get the OIDC auth working when using Kubeapps (regardless of your extra UI or attempt to use the KubeappsAPIs without the Kubeapps UI? I'm going to assume that you are not able to get Kubeapps itself (ie. the Kubeapps UI) working with OIDC yet. If so:

- Have you ensured that your pinniped setup is working correctly (ie. without Kubeapps or your app, just using Pinniped to authenticate following their docs and verifying the setup you have (with your `JWTAuthenticator` and Dex) works without any dependency on Kubeapps or your app.
- Once you've ensured that works, we can narrow the configuration error down to the Kubeapps config. So now, in Kubeapps, when you attempt the auth login and are redirected after a successful login, we next want to see the relevant logs from both kubeapps-apis and the pinniped-proxy service.

> When running the `curl -H "Authorization: Bearer $TOKEN" https://my.k8s.cluster/` command it suggests, it fails and if I try using the same approach as a dirty test to see if auth works from the Go app, it fails in the same way. The failure is that it is returning the login page and asking me to authenticate with the OIDC provider.

Note: I don't think you can do this curl command when using pinniped (it's part of the debugging instructions for non-pinniped setups), since when using pinniped, the auth with the cluster uses an X509 cert, not a token (so the cluster won't care about your token). That's why Kubeapps requires its pinniped-proxy service which, for each request to the kubeapps-apis service, will swap the token for a cert (via pinniped) while proxying the request to the cluster itself.

> **Description** I understand that the OIDC auth for all clusters needs to be configured to use the same provider which in our case is Dex and as the UI is working, I can only presume it's configured correctly. I'm able to login, list packages, deploy them and everything else you can do via the supplied UI.

Oh? So this is why I'm confused - do you mean that you can login, list packages, deploy them and everything else you can do via the supplied **kubeapps** UI? If so, then we have OIDC configured correctly and it's just for your own requests through your own UI (or curl) that you can't get the auth working? If that's the case, then what I would do is:

- In the kubeapps UI, look at one of the successful requests to the KubeappsAPIs, right-click on it and copy as curl or similar, to verify that the direct request to the KubeappsAPIs via CuRL works fine.
- That will have been a gRPC-Web request - I'm not sure if your own UI or proxy or whatever is using gRPC-Web (it's a bit simpler to use than handling the requests/responses via straight http), but maybe that's where the issue is, that the non gRPC-Web request isn't working?

> 
> I feel like I'm either missing a something around OIDC here

I don't think so, you seem to be trying to narrow it down to smallest working and non-working scenarios :)

> OR
> 
> Missing a chunk of documentation somewhere that will explain to me the steps I need to get OIDC auth working with the API.

We don't have docs for using the API without Kubeapps UI as yet (ie. developer docs for using KubeappsAPIs, outside of our own developer docs, which won't help you here).
 
> OR
> 
> Based on the [guide here](https://kubeapps.dev/docs/latest/reference/developer/kubeapps-apis/#an-aggregated-api-server---combining-results-from-different-packaging-plugins) whether I should be using the KubeApps API as a go module instead of hitting the REST endpoint.

No, not as a go module, but you may want to try using the gRPC-Web client instead of the ReST endpoints (to see if that may be where the issue is). You can look at our frontend code to see the working examples (assuming KubeappsUI is working for you). E.g. [this is the code that constructs the client using the token](https://github.com/vmware-tanzu/kubeapps/blob/main/dashboard/src/shared/KubeappsGrpcClient.ts#L30-L42).

There is a chance that there is something wrong with the combination of the ReST API and OIDC (as we've not used or tested that - devs tend to use token auth to test things quickly via the ReST API when developing something, then we only use the KubeappsUI, which is the gRPC-Web client, with our OIDC setups). Though I can't imagine what would be different as its a straight translation (but that's how bugs work - I shouldn't expect to be able to think of the issue before investigating it, necessarily)


> 
> OR
> 
> If I'm just not able to do what I'm trying to achieve and the the multi-cluster approach is designed in such a way that it works for the KubeApps UI and the API cannot be used as I wish to use it.

Nope - no restriction there. As you said you've used the same client in dex (and JWTAuthenticator in this case) for each cluster, the token (which pinniped converts to a X509 cert) should be valid for each cluster. 

> 
> **Additional context** I could just hit the Harbor API directly and I've got a working demo of this going already but before I started essentially replicating the API provided by KubeApps with regards to managing the apps, thought I'd open this to see if you can help me see the wood for the trees.

Yeah - well I hope the above helps to dig further towards the issue.

> Of course you can just tell me, after reading all of this, to go away 😆

Haha - I don't think we work like that :P

**Comment by drew-viles** [comment]
Hi @absoludity Thanks so much for the detailed response!

So yes, I have the KubeApps UI working with OIDC flawlessly it's just when I try to communicate with the API I'm seeing the failures I mentioned. I am just using straight http requests from Golang with the bearer token in an authorization header though for the quick and dirty test I mentioned so let me digest what you've written and sleep on it, then in the morning I can have a play around with the gRPC approach you mentioned. I did see that in the docs but I probably got my wires crossed when reading the guide I mentioned where it says "steal the token from the browser" and thought I could cheat a quick demo out before going head first into the rest of it 😄 

Thanks for indulging my essay!
