### ISSUE TITLE
How to manage Applications Not Deployed by Kubeapps

### ISSUE THREAD

**Issue by cwyj** [vmware-tanzu/kubeapps#6904]
**Summary**
How to manage Applications Not Deployed by Kubeapps?I tried to follow the apps that was managed by kubeapps, add some labels and annotation about kubeapps to my earlier apps yaml,but it still can not find  those apps  on  kubeapps dashboard.

**Description**
I add labels and annotations as below:

`apiVersion: apps/v1`
`kind: StatefulSet`
`metadata:`
`  annotations:`
`    meta.helm.sh/release-name: b2-bj-m01-vrr-01`
`    meta.helm.sh/release-namespace: b2-vrr`
`  labels:`
`    addonmanager.kubernetes.io/mode: Reconcile`
`    app.kubernetes.io/managed-by: Helm`
`    k8s-app: b2-bj-m01-vrr-01`
`    kubernetes.io/name: b2-bj-m01-vrr-01`

On kubeapps dashboard,can not find the app b2-bj-m01-vrr-01 in namespace b2-vrr,but some other namespaces you can see some apps.Such as kube-system,its may be added Automatically:
<img width="1647" alt="image" src="https://github.com/vmware-tanzu/kubeapps/assets/22216714/1d2988dc-b10c-4452-8ca1-80933a6ffe32">

So please let me know,How to manage Applications Not Deployed by Kubeapps?

**Comment by absoludity** [comment]
Hey there @cwyj . Unless I'm missing something, I don't think this is a kubeapps question, but rather a Helm question. That is, if you run `helm ls secret --all-namespaces -l "owner=helm"` you should see all the releases that Helm thinks have been installed.. Kubeapps is just a UI on the package manager, in this case, Helm.

My guess is that the helm client that Kubeapps uses is not finding your apps because your apps don't have a Helm release resource (usually a secret in the namespace which you'll see for a helm release by default with `kubectl get secret --all-namespaces -l "owner=helm"`).

Note: If you're going down the path of creating helm releases manually, you are getting into unsupported territory - just ensure Helm itself does what you think it should and Kubeapps should work.

**Comment by cwyj** [comment]
> Hey there @cwyj . Unless I'm missing something, I don't think this is a kubeapps question, but rather a Helm question. That is, if you run `helm ls secret --all-namespaces -l "owner=helm"` you should see all the releases that Helm thinks have been installed.. Kubeapps is just a UI on the package manager, in this case, Helm.
> 
> My guess is that the helm client that Kubeapps uses is not finding your apps because your apps don't have a Helm release resource (usually a secret in the namespace which you'll see for a helm release by default with `kubectl get secret --all-namespaces -l "owner=helm"`).
> 
> Note: If you're going down the path of creating helm releases manually, you are getting into unsupported territory - just ensure Helm itself does what you think it should and Kubeapps should work.

Thank you.This is indeed a problem about how does helm overwrite existing resources deployed by non-helm.And it seems impossible to overwrite.https://github.com/helm/helm/issues/10304
Maybe helm is only a deployment tool, not a mangement tool.

**Comment by absoludity** [comment]
> Maybe helm is only a deployment tool, not a mangement tool.

Management of helm deployments, but yeah, it's not a generic management tool for resources deployed outside of Helm.

**Comment by absoludity** [comment]
Closing as I *think* this is answered. Re-open if not.
